[항공사 웹사이트의 컴포넌트 접근성 높이기] 소파(차승하) 미션 제출합니다.
woowacourse/a11y-airline pull request #106
Opened 2024-09-29 11:19 UTC by ss0526100

안녕하세요 월하~ 반갑습니다~

지난 번 잘못 올린 pr에 이어서 두 번째 pr이네요 ㅋㅋ

지난 번에 pr에서 물어보신 css 정렬은 vscode 확장프로그램을 사용한 것이랍니다.

## 🔥 결과
![image](https://github.com/user-attachments/assets/a4d79c63-aa94-4822-a296-22df1520ca84)

- 배포한 페이지 접근 경로(GitHub): https://ss0526100.github.io/a11y-airline/
- 스크린 리더 화면 녹화 영상 (before / after)
before는 별도로 첨부하지 않았습니다!

https://github.com/user-attachments/assets/ba72d894-619c-4290-810d-379e76b75d3f

## ✅ 개선 작업 목록

**1 컴포넌트 접근성 개선 - 이미지 캐로셀**

- [x] 스크린 리더가 캐로셀의 전체 아이템 수를 읽을 수 있어야 합니다.
- [x] 스크린 리더가 이미지 캐로셀 내 각 아이템 정보를 읽을 수 있어야 합니다.
  - [x] 여행지, 좌석 유형, 가격 정보를 한번에 읽을 수 있어야 합니다.
  - [x] 이전/다음 아이템으로 이동하고 현재 보이는 아이템의 정보를 읽을 수 있어야 합니다.
  ```
     `여행 포커스 됨 옵션 ${travelOptions.length}개 중 ${index + 1}번째 옵션 ${
                option.departure
              }에서 ${option.destination} ${option.type} ${option.price}원` +
              ' 클릭 시 해당 페이지로 이동합니다'
  ```
다음과 같이 문구를 `travelOptions` 전체에 적용시키고 내부의 값에는 aria-hidden을 주었습니다.

- [x] 각 아이템을 선택하면 각각에 맞는 링크로 이동할 수 있어야 합니다.

**2 페이지 접근성 개선**

- [x] 페이지를 하나의 문서로 읽을 수 있어야 합니다.
  - [x] 페이지에 적절한 제목(title)을 제공하세요. 제목은 페이지의 주요 내용을 간결하게 설명해야 합니다.
  - [x] 페이지의 주요 영역을 시맨틱 태그를 사용해 명확히 구분해 주세요
  - [x] 헤딩을 논리적인 순서로 사용해 페이지 구조를 명확히 해주세요
- [x] 키보드 사용자를 위해 페이지 최상단에 '본문으로 바로가기' 링크를 제공해 반복되는 메뉴를 건너뛸 수 있게 해주세요

## 🧐 우리 팀의 접근성 체크리스트

<!--
우리 서비스에서 이런 부분의 접근성은 챙겨봐야겠다! 하는 체크리스트 v1을 만들고, 리뷰어와 의견을 나눠보세요
- 우리 팀 서비스에서 가장 중요하고 자주 사용되는 기능 플로우 1개를 선택하고 간단히 나열해 주세요

로그인->다락방(워크스페이스)선택->모임 목록 페이지->모임 목록 상세 페이지->참여

이 중에서 핵심 중의 핵심은
`모임 목록 상세 페이지`
라고 생각합니다.
![image](https://github.com/user-attachments/assets/6a0c287c-87d8-4f30-ba20-09126a5e0bdf)

모임 목록 상세 페이지의 체크리스트를 짜보자면
- [ ] 뒤로가기 버튼 aria-label 주기
- [ ] 모임 제목과 상태 aria label주기
- [ ] 찜버튼(하트) 토글 버튼으로 관리하기
- [ ] 모임 수정/취소 등 모임 관리 section aria-role 주기
- [ ] 참여자 리스트 aria-label관리
- [ ] 모임정보/상세설명 같이 aria-label로 관리하기
- [ ] 코멘트보내기 index 잘 주기
- [ ] 모집완료/참여 footer 버튼 aria-role 주기
정도가 될 것 같습니다!

그러면 잘부탁드려요!

2024-10-02 14:41 UTC, chlwlstlf approved these changes
안녕하세요 소파! 리뷰 요청을 빠르게 주셨는데 리뷰가 늦어져서 죄송해요😭😭

다음 버튼을 눌렀을 때 focus가 버튼에 있는 것이 아니라 여행 이미지로 다시 넘어오는 게 사용자에게 좋은 경험을 줄 수 있을 것 같아요ㅎㅎㅎ 이 부분에 대해 배워가는 게 많아서 지금 제 미션에도 적용해보려고 합니다. 감사합니다~!~!

요구사항을 다 만족하신 것 같아서 코드에 관해서 리뷰 조금 드렸습니다 확인해주세요😊

2024-10-02 14:41 UTC, chlwlstlf commented on index.html
> +  </head>
title 변경 굳입니다😊
다른 페이지로 넘어갔을 때는 title 내용이 바뀌어야 하지 않을까..? 라고 생각했는데 소파의 생각은 어떤가요~??

2024-10-02 14:41 UTC, chlwlstlf commented on src/components/TravelSection.tsx
>              </div>
`heading-3-text`를 사용하고 있어서 p 태그를 h3 태그로 변경해도 좋을 것 같아요!

div 태그에 `aria-hidden`이 있으면 그 자식 요소에도 적용이 되는 걸로 알고 있습니다..! 삭제해도 원하는 동작이 되고 있다면 없애도 될 것 같아요😊

2024-10-02 14:41 UTC, chlwlstlf commented on src/components/FlightBooking.tsx
여기서는 바뀐 코드가 없지만.. statusMessage가 한 번 더 읽히고 있습니다!! 버그라고 생각해서 말씀드려요😂

https://github.com/user-attachments/assets/d3d40787-1654-4999-9ca1-e31a1808710b

2024-10-02 14:43 UTC, chlwlstlf requested changes
안녕하세요 소파! 리뷰 요청을 빠르게 주셨는데 리뷰가 늦어져서 죄송해요😭😭

다음 버튼을 눌렀을 때 focus가 버튼에 있는 것이 아니라 여행 이미지로 다시 넘어오는 게 사용자에게 좋은 경험을 줄 수 있을 것 같아요ㅎㅎㅎ 이 부분에 대해 배워가는 게 많아서 지금 제 미션에도 적용해보려고 합니다. 감사합니다~!~!

요구사항을 다 만족하신 것 같아서 코드에 관해서 리뷰 조금 드렸습니다 확인해주세요😊

2024-10-03 10:54 UTC, ss0526100 commented on src/App.tsx
> +      >
저는 브라우저단이 아닌 리액트 단에서 최대한 모든 사용자의 플로우를 조작하고 싶었습니다. 이러한 생각은 밑에서 포커스를 위해 ref를 사용한 부분과 일맥상통합니다.

Navigation안에 콘텐츠로 이동하기 버튼을 둔 이유는 navigation이 있어야 skipNavigation이 의미가 있다고 생각하기 때문에 넣었습니다. 

그런데 이제와서 생각해보니 조금 억지스러울 수 있는 부분이겠다는 생각도 드네요..

추후에 컴포넌트 분리가 필요해보입니다.

2024-10-03 11:01 UTC, ss0526100 commented on src/components/TravelSection.tsx
> +
> 각 카드에 id 값을 부여한 후 그 카드 요소에 focus를 하는 방법은 어떤가요??
텐텐이 제시해주신 방법도 좋은 방법인 것 같아요!

그런데 개인적인 선호(리액트를 통한 돔조작+id값은 전역변수이므로 관리하기 어려움)때문에 저는 지금의 코드를 더 선호할 것 같아요.

option의 개수가 많아지면 어이없는 방법이긴 하지만 이런 코드도 가능할 것 같아요 ㅋㅋ(https://github.com/ss0526100/react-payments/blob/7d7ccb44673441a0b553aac3997a554d3d323104/src/hooks/useHTMLRefs.tsx)

2024-10-03 11:02 UTC, ss0526100 commented on index.html
> +  </head>
저도 텐텐의 생각에 동의합니다~

spa인 경우 페이지 내부의 정보가 바뀌면 html상의 tilte도 바뀌는 것이 좋을 것이라는 생각이 들어요

2024-10-03 11:03 UTC, ss0526100 commented on src/components/TravelSection.tsx
>              </div>
힌트가 있었군요..이런;;

수정하겠습니다

2024-10-03 12:52 UTC, chlwlstlf commented on src/App.tsx
> +      >
아하! navigation이 없어도 콘텐츠로 이동할 수 있다면 좋을 것 같다는 생각에 질문 드렸습니다🤗 하지만 이 미션에서는 navigation 안에 있어도 크게 상관은 없었을 것 같네요ㅎㅎ 답변 감사합니다!

2024-10-03 12:59 UTC, chlwlstlf commented on src/components/TravelSection.tsx
> +
ㅋㅋㅋㅋㅋㅋ코드 잘못 본 줄 알았어요..😮

id 값은 가상DOM에서도 상충되는 흐름이라고 하더라고요..! 소파 덕분에 공부할 수 있었어요ㅎㅎㅎ

아래는 useRef을 배열로 관리하는 예시라고 합니다. 이렇게 하면 각 개수만큼 ref를 부여하지 않아도 될 것 같아요! 다음에 개수가 많아지면 참고해도 좋을 것 같아서 코드 첨부해드립니다~

```tsx
const cardRefs = useRef([]);

const focusCard = (index) => {
  if (cardRefs.current[index]) {
    cardRefs.current[index].focus();
  }
};

return (
  {cards.map((card, index) => (
    <div ref={el => cardRefs.current[index] = el} tabIndex={0}>
      {card.content}
    </div>
  ))}
);
```

2024-10-03 13:07 UTC, chlwlstlf approved these changes
안녕하세요 소파!! 소파의 의견도 들어보고 저도 공부하면서 코드 리뷰를 하니 재밌었습니다ㅎㅎ 소파가 ref를 좋아하는 것도(?) 알게 되는 시간이었어요😊👍 

변경 사항 확인했습니다! 답변도 자세하게 남겨주셔서 감사합니다. 레벨4 남은 미션도 화이팅이에요🎯

---

> fix:텐텐의 기운을 받아 버그 해결

커밋 메세지 잘못 본 줄 알았😮

2024-10-03 13:07 UTC, merged