[항공사 웹사이트의 컴포넌트 접근성 높이기] 포메(김우성) 미션 제출합니다.
woowacourse/a11y-airline pull request #109
Opened 2024-09-29 13:49 UTC by novice0840

## 🔥 결과

- 배포한 페이지 접근 경로(GitHub Pages): https://novice0840.github.io/a11y-airline/
- 스크린 리더 화면 녹화 영상 (before / after)

before:

https://github.com/user-attachments/assets/abaed728-34a1-43d7-9b4a-4b2cceb89aa8

after:

https://github.com/user-attachments/assets/7d8642fa-068a-4b55-ba71-a5926d81856c

## ✅ 개선 작업 목록

**1 컴포넌트 접근성 개선 - 이미지 캐로셀**

- [ ] 스크린 리더가 캐로셀의 전체 아이템 수를 읽을 수 있어야 합니다.
- [ ] 스크린 리더가 이미지 캐로셀 내 각 아이템 정보를 읽을 수 있어야 합니다.
  - [ ] 여행지, 좌석 유형, 가격 정보를 한번에 읽을 수 있어야 합니다.
  - [ ] 이전/다음 아이템으로 이동하고 현재 보이는 아이템의 정보를 읽을 수 있어야 합니다.
- [ ] 각 아이템을 선택하면 각각에 맞는 링크로 이동할 수 있어야 합니다.

**2 페이지 접근성 개선**

- [ ] 페이지를 하나의 문서로 읽을 수 있어야 합니다.
  - [ ] 페이지에 적절한 제목(title)을 제공하세요. 제목은 페이지의 주요 내용을 간결하게 설명해야 합니다.
  - [ ] 페이지의 주요 영역을 시맨틱 태그를 사용해 명확히 구분해 주세요
  - [ ] 헤딩을 논리적인 순서로 사용해 페이지 구조를 명확히 해주세요
- [ ] 키보드 사용자를 위해 페이지 최상단에 '본문으로 바로가기' 링크를 제공해 반복되는 메뉴를 건너뛸 수 있게 해주세요

## 🧐 우리 팀의 접근성 체크리스트

### 우리 팀 서비스에서 가장 중요하고 자주 사용되는 기능 

 게임 대기방 -> 게임 시작 -> 밸런스 선택지 선택 -> 선택 결과 확인

1. 화면을 볼 수 없는 사용자가 이 단계를 완료할 수 있는가?

밸런스 게임은 2가지 선택지가 있는데 각각 별개의 HTML 태그로 나뉘어져 있어 스크린 리더기에서는 한 눈에 알아보기가 힘들다. 게다가 시간 제한이 최대 15초이므로 리더기를 사용하며 게임을 진행할 경우 제한 시간 내에 선택지를 고르지 못할 확률이 높다. 

 2. 이 단계에서 제공하는 정보나 지시 사항이 모든 사용자에게 명확한가?

정보와 지시 사항이 눈으로 보았을 때는  한 눈에 들어오지만 리더기로 실행했을 때는 여러 태그에 흩어져 있어 불명확할 가능성이 있다.

2024-10-02 01:52 UTC, greetings1012 requested changes
포메! 바쁜 와중에 미션 정말 수고하셨어요!
리뷰 남겨놓았으니 시간날 때 반영해주세요 👍

2024-10-02 01:52 UTC, greetings1012 commented on src/App.tsx
> +      </a>
이 부분에 포커스가 이동해도 시각적으로 아무것도 보이지 않는데, 의도하신 걸까요? 🤔
키보드 접근성을 높이는 작업인 만큼, 포커스가 이동했을 경우에는 사진처럼 시각적으로도 보이는 게 좋을 것 같아서요!
<img width="849" alt="image" src="https://github.com/user-attachments/assets/b80fb859-2862-487f-a2fe-700f5d6a9ff7">

2024-10-02 01:52 UTC, greetings1012 commented on src/components/FlightBooking.tsx
> +          </div>
이렇게 하면 VoiceOver를 사용자에게는 도움말 내용이 제대로 들리지 않을 것 같아요! 😭

2024-10-02 01:52 UTC, greetings1012 commented on src/components/TravelSection.tsx
다음 버튼을 선택하면 VoiceOver는 캐러샐 카드의 내용을 읽고 있는데, 포커스는 버튼에 있어 사용자가 혼란스러울 수 있을 것 같아요!
useEffect로 포커스 강제 이동 효과를 주면 좋지 않을까요? 😁

2024-10-02 01:52 UTC, greetings1012 commented on src/components/TravelSection.tsx
> +            <div aria-live="polite" className={styles.srOnly}>
총 몇 개의 캐러셀 아이템 중 몇 번째인지도 같이 읽어주면 좋을 것 같아요!
> 스크린 리더가 캐로셀의 전체 아이템 수를 읽을 수 있어야 합니다.

2024-10-02 01:52 UTC, greetings1012 commented on src/components/TravelSection.tsx
> +      <button
alt 속성이 없네요 😭
꾸미기에 사용된 아이콘, 이미지의 경우 alt='' 를 삽입해 브라우저가 꾸미기용 이미지를 따로 읽지 않도록 하는 것이 좋아요!

2024-10-02 01:52 UTC, greetings1012 commented on src/components/TravelSection.tsx
> +      <button
alt 속성이 없네요 😭
꾸미기에 사용된 아이콘, 이미지의 경우 alt='' 를 삽입해 브라우저가 꾸미기용 이미지를 따로 읽지 않도록 하는 것이 좋아요!

2024-10-02 01:52 UTC, greetings1012 commented on src/components/TravelSection.tsx
> +        aria-describedby="and 뒤로"
이 속성은 왜 추가되었을까요? 🤔
현재로서는 아무 역할도 하지 않을 것 같아요.

2024-10-02 04:31 UTC, novice0840 commented on src/App.tsx
> +      </a>
수정했습니다! 이제 보여요

![image](https://github.com/user-attachments/assets/870a5ff6-bb6e-4592-9775-eb51ceaefe46)

2024-10-02 04:53 UTC, novice0840 commented on src/components/FlightBooking.tsx
> +          </div>
aria-label와 aria-live를 사용하여 showToolTip 가 true 된 경우 안내 메세지를 읽도록 변경하였습니다

2024-10-02 05:01 UTC, novice0840 commented on src/components/TravelSection.tsx
> +        aria-describedby="and 뒤로"
수정했습니다!

2024-10-02 05:04 UTC, novice0840 commented on src/components/TravelSection.tsx
> +      <button
수정했습니다!

2024-10-02 05:04 UTC, novice0840 commented on src/components/TravelSection.tsx
> +      <button
수정했습니다!

2024-10-02 05:37 UTC, novice0840 commented on src/components/TravelSection.tsx
> +            <div aria-live="polite" className={styles.srOnly}>
안내 메세지에 추가했습니다!

2024-10-02 05:56 UTC, novice0840 commented on src/components/TravelSection.tsx
focus가 바뀌어도 안내 메세지에 나타나지 않으면 사용자가 혼동할 수도 있을 것 같아. 상품 메세지만 나오고 focus는 그대로 두었습니다. 
그리고 상품의 개수가 많아질 경우 다음 버튼을 여러 번 눌러야 하기 때문에 focus를 옮기면 뒤쪽 상품을 고르기가 불편해질 것 같다 판단했습니다.

2024-10-03 19:25 UTC, greetings1012 commented on src/components/TravelSection.tsx
사람마다 의견이 다를 수 있겠네요! 
제 의견을 조금 말씀드리자면,

> 저는 focus가 바뀌어도 안내 메세지에 나타나지 않으면 사용자가 혼동할 수도 있을 것 같아. 상품 메세지만 나오고 focus는 그대로 두었습니다.
'모든 정보를 음성으로 전달받는 사용자의 경우, `선택하면 예약 페이지로 이동합니다.` 를 듣고 현재 포커스를 선택하면 예약 페이지로 이동하는 것을 기대하지 않을까?' 라고 생각했어요.

> 그리고 상품의 개수가 많아질 경우 다음 버튼을 여러 번 눌러야 하기 때문에 매번 focus를 옮기면 뒤쪽 상품을 고르기가 불편해질 것 같다 판단했습니다.

시각적으로 불편한 사용자의 경우 메시지를 모두 들어야 다음/이전으로 넘길지 말지를 결정할 수 있기 때문에 이 부분은 고려하지 않았어요!

> 그래서 절충안으로 "버튼" 메세지 뒤에 추가적인 설명을 덧붙였는데 파란은 어떻게 생각하나요?

`다음 여행 클릭 시 상품 설명이 안내됩니다`라는 메시지에는 '포커스는 다음 버튼에 있지만, 캐러셀에 대한 설명이 재생된다' 라는 숨은 뜻을 모두 보여주기에는 조금 부족하다고 생각해요.
또한 VoiceOver 사용자는 '클릭' 이라는 표현보다는 '선택'이 조금 더 좋을 것 같아요.

만약 포메가 포커스는 다음 버튼에 두고 캐러셀 설명을 읽는 방식을 유지하고 싶다면
캐러셀의 `선택하면 예약 페이지로 이동합니다.` 라는 메시지를 없애는 것이 가장 적절한 방법이라고 생각해요!

2024-10-03 19:27 UTC, greetings1012 approved these changes
수고하셨습니다, 포메!
ssr 미션, 프로젝트 등 바쁜 일들이 겹쳤는데도 말씀드린 내용들을 모두 반영하고 답변주셨네요!
캐러셀 부분 코멘트는 생각이 다를 수 있는 부분이라 생각해 먼저 Approve 드리겠습니다 😁

남은 레벨 4도 같이 화이팅해요!

2024-10-04 04:20 UTC, merged