[항공사 웹사이트의 컴포넌트 접근성 높이기] 도비(김정혁) 미션 제출합니다.
woowacourse/a11y-airline pull request #14
Opened 2021-09-29 16:01 UTC by zereight

서니 안녕하세용~

지금 저는 8시간을 이 미션에 쏟아부었습니다.
왜냐하면 `성인 승객 추가 ${count}명` 이 문구가 찍히지 않기 떄문입니다.

제 Voice Over는 `count` 상태값이 변경되었는데 왜 못읽는걸까요.
제 코드가 문제일것같아서, 앞선분들의 PR을 다 까보았습니다.
하지만 앞선분들의 코드를 복붙해오고, 다른 분들이 호스팅한 웹페이지에서 제 Voice Over를 돌려봐도 `성인 승객 추가 ${count}명`는 찍히지 않았습니다.

결국은 제 Voice Over 셋팅문제라는 것이죠 껄껄.
도대체 어떤 셋팅이 뭐가문제인지 모르겠습니다. 

https://user-images.githubusercontent.com/42544600/135305910-cae190f9-a52a-46dd-9978-5a9707187875.mov

<img width="1135" alt="스크린샷 2021-09-30 오전 12 40 07" src="https://user-images.githubusercontent.com/42544600/135305930-3e2e763a-2c2f-40bd-a7ba-a19dd7320023.png">
<img width="456" alt="스크린샷 2021-09-30 오전 12 37 35" src="https://user-images.githubusercontent.com/42544600/135305936-0f0fca7a-7489-4554-a2bd-8a3c95ebf3e6.png">

[x] 라이트 하우스 접근성 100점 
[x] 스크린 리더로 페이지 컨텐츠를 이용하는데 무리가 없는가? 
[x] document title이 제대로 적혀있는가? 
[x] wave tools 검사 결과 에러 0 
[x] html document lang 이 ko 로 되어있는가? + aria, 대체 텍스트 등이 한글로 명확히 작성되어있는가? 
[x] 접근성 린터를 사용했는가? 
[x] 키보드 만으로 페이지 컨텐츠를 이용하는데 무리가 없는가?

2021-09-29 16:08 UTC, zereight commented
Voice Over 셋팅을 
하 
<img width="577" alt="스크린샷 2021-09-28 오후 2 46 43" src="https://user-images.githubusercontent.com/42544600/135307066-7221ffa6-39fd-41f3-8648-74f01960591a.png">

2021-09-30 02:13 UTC, sunhpark42 requested changes
코드가 엄청 깔끔하네요. 
전체적으로 aria 속성도 잘 사용되어 있는 것 같습니다.
다만 스크린리더기 차이 문제인지, 안읽히는 것들이 조금 있어요 ㅠㅠ 리뷰에 남겨뒀는데, 도비가 올려주신 영상에서도 확인이 안되는 것들이 있어서 확인 한 번 해주세요~

그리고 중간에 코드 날아간게 있어요. input에 aria-describe까지만 쓰여있어서 수정이 필요할 것 같습니다!

2021-09-30 02:13 UTC, sunhpark42 commented on src/components/SpinButton.tsx
> +      alert(`최소 인원은 ${LIMIT_COUNT.MIN}명입니다.`);
alert를 이용하셨네요. 혹시 NVDA에서는 alert가 잘 읽히나요? 맥 보이스오버에서는 alert의 내용 컨텐츠가 하나도 안읽힙니다. ㅠㅠㅠ 영상을 보니까 NVDA 리더기에서도 에러 메세지를 안읽는것 같던데, 확인해보시면 좋을 것 같아요~

![](https://user-images.githubusercontent.com/67677561/135373566-80b9ea34-18f0-42b7-a60b-8f43e6c60c04.png)

2021-09-30 02:13 UTC, sunhpark42 commented on src/components/SpinButton.tsx
> +      ></span>
굿. 그런데 감소를 할 때에도 성인 승객 추가라고 읽혀서, 감소 버튼을 눌렀을 때 약간 혼란스러울 것 같다는 생각도 듭니다.

2021-09-30 02:13 UTC, sunhpark42 commented on src/components/SpinButton.tsx
> +        aria-errormessage={`최소 탑승 인원은 ${LIMIT_COUNT.MIN}명까지 입니다.`}
aria-errormessage라는 속성은 언제 읽히는 건가요? 스크린 리더에서 확인이안되네용

2021-09-30 02:13 UTC, sunhpark42 commented on src/components/SpinButton.tsx
> +        aria-errormessage={`최대 탑승 인원은 ${LIMIT_COUNT.MAX}명까지 입니다.`}
그런데 aria-errormessage라는 속성은 언제 읽히는 건가요? 스크린 리더에서 확인이안되네용

2021-09-30 02:14 UTC, zereight commented on src/components/SpinButton.tsx
> +        aria-describe
이거 뭐여 ㅋㅋ

2021-09-30 02:15 UTC, zereight commented on src/components/SpinButton.tsx
> +      alert(`최소 인원은 ${LIMIT_COUNT.MIN}명입니다.`);
이거 Voice Over 셋팅 설정하면 읽힙니당. 설정 차이 ㅜㅜ

2021-09-30 02:15 UTC, zereight commented on .babelrc
> +{}
아닛

2021-09-30 02:16 UTC, zereight commented on .prettierrc
> +
아닛

2021-09-30 02:16 UTC, zereight commented on src/index.tsx
> +);
아닛

2021-09-30 02:17 UTC, zereight commented on src/components/SpinButton.tsx
> +      ></span>
요구사항 지키는것에 집착한 결과입니다. 수정하겠슴니다!

2021-09-30 02:25 UTC, sunhpark42 commented on src/components/SpinButton.tsx
> +      alert(`최소 인원은 ${LIMIT_COUNT.MIN}명입니다.`);
제가 설정해보겠습니다..뭘 설정해야하는거지...

2021-09-30 02:25 UTC, sunhpark42 commented on src/components/SpinButton.tsx
> +      alert(`최소 인원은 ${LIMIT_COUNT.MIN}명입니다.`);
제가 설정해보겠습니다..뭘 설정해야하는거지...

2021-09-30 05:08 UTC, zereight commented
> 그런데 감소를 할 때에도 성인 승객 추가라고 읽혀서, 감소 버튼을 눌렀을 때 약간 혼란스러울 것 같다는 생각도 듭니다.

추가/감소라고 텍스트를 바꾸려했는데, 접근성을 위해서 ref나 새로운 상태를 만드는 것이 불필요하다고 생각되어서,
단어를 "변경"으로 바꾸었습니다 ㅎㅎ

2021-09-30 14:31 UTC, zigsong commented on src/components/SpinButton.tsx
> +      alert(`최소 인원은 ${LIMIT_COUNT.MIN}명입니다.`);
@zereight @sunhpark42 저도 알려주세용

2021-09-30 14:35 UTC, zigsong commented
도비 동영상은 소리가 안 켜져용

2021-09-30 15:23 UTC, zereight commented
소리를 녹음 안했어용

2021-10-01 02:54 UTC, sunhpark42 approved these changes
굿굿

2021-10-03 13:28 UTC, merged