[항공사 웹사이트의 컴포넌트 접근성 높이기] 동동(김동희) 미션 제출합니다.
woowacourse/a11y-airline pull request #15
Opened 2021-09-29 16:47 UTC by bigsaigon333

2021-09-30 02:14 UTC, devhyun637 requested changes
동동!!

항상 더 많이 배워갑니다! 제가 감히 리뷰를 할 수 있는 코드가 아닌거 같아요 👍 
소소한 코멘트 남겨뒀으니 참고부탁드려용!

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                <h1 className="text-2xl">
h1 태그는 문서에 1개! ๑·̑◡･̑๑

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +
이부분 저는 그냥 증가 & 감소 없애버렸는데, 이전 상태랑 비교한거 좋네용!

갑자기 든 생각인데 `성인 승객 증가 1명`, `성인 승객 감소 1명` 라고 읽히면 성인 승객이 1명 증가했다는 것일지, 성인 승객이 증가해서 1명이 되었다는 건지 헷갈릴 수도 있다는 생각이 들었습니다! (❁´▽`❁) 
동동의 의견도 궁금합니다

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                validationMessage: `성인 승객은 ${MIN_COUNT}명 미만이 될 수 없습니다`,
Wow 👍👍👍

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                    inputMode="tel"
inputMode 좋습니다!! 배워가야징~
하지만 왜 type은 text일까요?

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                  <input
input에 label이 없어도 오류로 안뜨네요! 
input에는 어떤 input인지 설명하는 부분도 추가되면 좋을 것 같습니다! 
label이 없더라도 aria-label도 좋을 것 같아용

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                <span className="ml-4 text-xl text-gray-500 border border-gray-500 rounded-full w-6 h-6 flex items-center justify-center">
tootip은 button 처럼 여겨질텐데, 마우스를 올리면 cursor가 pointer가 아니라서 살짝 당황..
현재 쓰이지 않는 것이라면 지워도 좋지 않을까요? 예쁜 마크업을 위해서였을까용??

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                  <p className="sr-only" role="status">
스크린 리더가 읽어줄 부분을 이렇게 처리한 것도 좋네요!!

2021-09-30 02:14 UTC, devhyun637 commented on src/index.html
> +                    {state.validationMessage}
안내 메세지까지 잘 나오는거 확인했습니다!
몇명 이상, 이하는 불가능하다는 메세지도 너무 좋습니다!

2021-10-01 11:46 UTC, bigsaigon333 commented on src/index.html
> +                <span className="ml-4 text-xl text-gray-500 border border-gray-500 rounded-full w-6 h-6 flex items-center justify-center">
네 그냥 똑같이 만든다고 만들었는데, 귀찮아서 접근성 부분은 안했어요 ㅠㅠ 

그냥 지워버리겠습니다 ㅎㅎ...

2021-10-01 11:48 UTC, bigsaigon333 commented on src/index.html
> +                <span className="ml-4 text-xl text-gray-500 border border-gray-500 rounded-full w-6 h-6 flex items-center justify-center">
관련 커밋입니다: https://github.com/woowacourse/a11y-airline/pull/15/commits/4d8f32ab7b130d91adff7a4da0c67d6c19d12dbe

2021-10-01 11:53 UTC, bigsaigon333 commented on src/index.html
> +                  <input
input에 label 있어여 :sob: 

123행의 `<label htmlFor="adult-value-input">성인</label>` 입니다!

위치가 좀 멀게 보이긴 하네요 ㅎㅎ..

2021-10-01 12:47 UTC, bigsaigon333 commented on src/index.html
> +                    inputMode="tel"
type="number" 로 했을 때 옆에 나오는 화살표가 너무 지저분하게 보였고, 스타일 수정하기가 귀찮아서 그냥 text로 했습니다 ㅎㅎ...
voice over에서는 type이 text이던 number 이던 모두 '텍스트필드' 라고 읽어줘서 딱히 상관없지 않나는 생각이 들었는데,,,


개발자 도구의 accessibility 로 보니 role이 textfield 에서 spinbutton 으로 바뀌었네요!!
![image](https://user-images.githubusercontent.com/31029000/135621814-6a947a3e-b6e5-42ce-9cc1-aab81f6e33ca.png)

너무 특정 스크린 리더에만 치우쳐서 개발을 하면 안된다는걸 깨달았습니다..

type을 number로 수정하겠습니다..!

2021-10-01 12:55 UTC, bigsaigon333 commented on src/index.html
> +                    inputMode="tel"
관련 커밋입니다: https://github.com/woowacourse/a11y-airline/pull/15/commits/8cd3828acb7cef2f66cbd5bc4770e8164f134857

2021-10-01 13:53 UTC, bigsaigon333 commented on src/index.html
> +
일리가 있는 말씀이시네요! 

저는 버튼이 눌러졌을 때 제대로 성인이 증가/감소하였는지도 알려주고, 그 행동의 결과가 어떤지도 알려주면 좋겠다고 판단하여서

'성인 승객 증가 **현재**  1명' 으로 수정하였습니다! :smile: 

Voice Over로 들으니 쉼표 없이 바로 읽어서 조금 어색하게 들리긴 하네요 :dizzy_face:

2021-10-01 13:54 UTC, bigsaigon333 commented on src/index.html
> +
관련 커밋입니다: https://github.com/woowacourse/a11y-airline/pull/15/commits/5e7f2c71600c4c32c0c18514447fd40115673ded

2021-10-01 14:06 UTC, bigsaigon333 commented on src/index.html
> +    ></script>
웹팩과 같은 번들러를 사용하지 않고, react, react-dom 을 script로 갖고 와서 사용하려고 이렇게 했어요!

어차피 next.js 로 마이그레이션할 꺼라서 CRA 깔고 나중에 지우고 이게 되게 번거롭게 느껴졌거든요 :+1: 

최적화가 안되어 있는 development 코드를 가지고 왔지만, 이번 미션은 웹 접근성만 신경쓰면 되니까 성능은 전혀 고려하지 않았습니다 :smile: 

레퍼런스는 요거에요 -> https://kentcdodds.com/blog/super-simple-start-to-react

2021-10-01 14:07 UTC, bigsaigon333 commented on src/index.html
> +    <script type="text/babel">
https://kentcdodds.com/blog/super-simple-start-to-react   
https://babeljs.io/docs/en/babel-standalone#script-tags
<- 요기서 알려준거에요 ㅎㅎ

2021-10-01 14:29 UTC, bigsaigon333 commented on src/index.html
> +                <h1 className="text-2xl">
https://html.spec.whatwg.org/multipage/sections.html#headings-and-sections

> Sections may contain headings of any rank, but authors are strongly encouraged to either use only h1 elements, or to use elements of the appropriate rank for the section's nesting level.


HTML Living Standard 에 따르면 section 마다 하나의 h1을 두는게 강하게 권장되고 있다고 해요. 

header는 새로운 section을 만들지 않으니, header 내 h1은 body의 h1을 나타내고,
main은 새로운 section 을 만드니, main 내  h1은 main 내 h1입니다. 

아래의 예시와 같이 section 내 각각의 heading 을 가지고 있더라도 시맨틱하게 동일하다고 합니다 :smile: 
(유지관리가 편하기 때문에 더욱 권장되는 패턴이라고  하네요...)
![headings-and-sections](https://user-images.githubusercontent.com/31029000/135634446-1adeafa1-6262-418c-90a6-052e8c690c15.png)

근데 Voice Over에서 해보니 heading 1 이라고 읽어주네요.. h2로 수정하겠습니다 :+1:

2021-10-01 14:34 UTC, bigsaigon333 commented on src/index.html
> +                <h1 className="text-2xl">
관련 커밋입니다: https://github.com/woowacourse/a11y-airline/pull/15/commits/722a15f63aaa7ce8734c261d17c82a5ccd77d72e

2021-10-03 12:49 UTC, devhyun637 commented on src/index.html
> +    ></script>
오 좋은 것을 배워감니다!!

2021-10-03 12:49 UTC, devhyun637 commented on src/index.html
> +    <script type="text/babel">
이것도 참고자료 감사합니다 동동짱

2021-10-03 13:04 UTC, devhyun637 commented on src/index.html
> +                <h1 className="text-2xl">
오오 새로운 사실을 알아갑니다👍👍👍👍

저는 예전에 [이 글](https://nuli.navercorp.com/community/article/1133024)을 참고하여 h1 태그는 하나의 html당 1개만 있어야한다고 생각해보니, 지금보니 여러개를 사용하는 것도 가능하군요. 그리고 대부분의[ 스크린 리더 유저들은 문서에서 정보를 얻을 때](https://webaim.org/projects/screenreadersurvey9/#finding) heading 태그의 도움을 많이 받는다니, 어떻게하면 제목 태그를 더 효율적으로 쓸 수 있을지도 고민해보면 좋을 것 같다는 생각을 덕분에 해보았습니당:)

SEO 측면에서도 h1 태그는 페이지에 한개가 좋다는 기사를 본적이 있는 것 같은데, 해당 글은 찾지를 못해서 찾게되면 공유하도록 하겠습니다.

동동 덕분에 당연한 것은 없다는 것을 다시한번 반성하게 되네요 감사합니다 :)

2021-10-03 13:05 UTC, devhyun637 commented on src/index.html
> +
오 친절함의 끝판왕 동동의 스크린리더 👍👍👍

2021-10-03 13:08 UTC, devhyun637 commented on src/index.html
> +                    inputMode="tel"
아 저도 그 '증감자'라고 읽히는 부분이 거슬려서 어떻게 깔끔하게 읽을 수 있는 방법은 없을까 고민을 했었는데, 접근성 마스터 서니와 함께 이야기하던 중, `오히려 그 부분에서도 숫자를 줄이고 늘릴 수 있게 해주는 것이 더 좋지 않을까?` 라는 말을 들어서 그런 방향으로도 생각할 수 있구나를 느꼈습니다. 저는 그냥 input을 아에 readOnly로 막아버렸는데, 사용자의 입장에서는 숫자의 input에서도 변환할 수 있는 선택지가 있으면 좋을것 같기도 하네용 :) 👍👍👍

> 너무 특정 스크린 리더에만 치우쳐서 개발을 하면 안된다는걸 깨달았습니다..

단지 저는 `스크린 리더 === 접근성 이 아닌만큼`, 시멘틱하게 원래의 속성에 맞게 태그를 사용하는 게 더 먼저이지 않을까하고, 동동은 어떤 생각이신지 궁금해서 여쭈어봤던 것입니당!

2021-10-03 13:11 UTC, devhyun637 commented on src/index.html
> +                  <input
아... 이것은 제가 제대로 코드를 안읽은 탓입니다.. 🥲🥲🥲🥲 흙 죄송합니다

2021-10-03 13:18 UTC, devhyun637 approved these changes
제가 리뷰를 해드린 것보다, 동동의 꼼꼼한 너무 많은 것을 배워가게 되어서 영광입니다. 👍👍👍👍

제가 알고 있던 지식도 한번 더 고민해봐야한다는 반성을 하게 되었던 거 같아요:) 
의견에 대한 저의 소소한 답변 달았으니, 가볍게 주무시기 전에 확인해주시면 감사하겠습니다~~!!🌕

2021-10-03 13:19 UTC, merged

2021-10-03 14:32 UTC, bigsaigon333 commented on src/index.html
> +                    inputMode="tel"
> 단지 저는 스크린 리더 === 접근성 이 아닌만큼, 시멘틱하게 원래의 속성에 맞게 태그를 사용하는 게 더 먼저이지 않을까하고, 동동은 어떤 생각이신지 궁금해서 여쭈어봤던 것입니당!

저는 input type="text" 랑 input type="number"의 role이 다른지도 모르는 똥멍청이입니다 ㅠ