[항공사 웹사이트의 컴포넌트 접근성 높이기 - 1단계] 록바(김상록) 미션 제출합니다.
woowacourse/a11y-airline pull request #26
Opened 2022-10-01 10:35 UTC by lokba

## 🔥 결과
### [배포 사이트](https://capable-pixie-ad7eb2.netlify.app/)

## ✅ 요구사항 목록

**1 Spin Button**

- [x] 최대 인원수는 3명까지만 가능하게 구현합니다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
성인 탑승자 한명 줄이기 버튼
성인 1 텍스트 숫자만 수정
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 2
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 3
```

## 🧐 공유
천천히 작성하겠습니다.

2022-10-05 11:13 UTC, DomMorello requested changes
록바 안녕하세요! 리뷰어 돔하디입니다 ㅎㅎㅎ

웹팩 설정, TS, React 모두 수동으로 환경설정해준 부분이 인상적이었습니다. 그리고 간단한 컴포넌트를 구현하는 미션임에도 불구하고 최대한 확장성있는 구조를 염두에 두고 구현했다는 점이 눈에 띄었습니다 :)

aria 특성을 잘 활용해서 스크린 리더로 해당 화면을 읽을 때 별 문제 없이 잘 작동하는 것을 확인했습니다.

코드레벨에서 제 개인적인 생각과 공유하고 싶은 내용은 코멘트로 달았습니다!

몇 가지 아쉬운 부분 피드백 드려볼까 합니다! ㅎㅎㅎ

### 오류 알려주기
이건 지극히 제 개인적인 생각입니다만 스크린 리더 사용자가 어떤 입력을 할 때 해당 입력값에 대한 제한사항(예를 들어, 승객은 1명 부터 3명까지만 입력 가능함)이 있을 때 사용자에게 그런 부분을 알려준다면 좀 더 친절한 서비스가 되지 않을까라는 생각을 했습니다.

물론 button에 disabled 를 줘서 입력을 잘 막아줘서 사용자가 제한사항을 알 수 있겠지만 만약에 승객 제한사항이 10명이었다면 10번을 눌러봐야 10명 이상 승객을 선택할 수 없다는 것을 알 수 있는 것이 조금 불편할 수 있다고 생각합니다 ㅎㅎㅎ

저는 그래서 alert를 썼는데 이 방법 말고도 aria 를 이용해서 뭔가 에러를 읽어줄 수 있는 기능도 있는 것 같더라고요 ㅎㅎㅎㅎ

### tooltip
요구사항에 글씨로 명시돼있지는 않았지만 시안에 tooltip 이 있었습니다. 이 부분에 대한 구현이 없더라고요! 

저는 개인적으로 tooltip 을 구현하면서 웹 접근성에서 tooltip을 처리하는 방법에 대해서 여러 고민을 했어서 학습에 많은 도움이 되었습니다 ㅎㅎㅎ

꼭 설명해야 하는 거라면 tooltip이 아니라 텍스트로 설명을 보여주라는 제안이 있을 정도로 웹 접근성에서 tooltip이 갖는 문제점이 확실한 것 같은데 이런 부분들을 공부해볼 수 있었습니다!

> 완성도 있는 프로젝트에서 많이 배워갑니다! 수고 많으셨습니다 ㅎㅎㅎㅎ
제가 공부한 내용에 대해서 공유하기 위해서 피드백을 드렸는데 꼭 반영하실 필요는 없다고 생각합니다. 각자의 판단이 있는거니까요 ㅎㅎㅎㅎ
피드백 반영이 불필요하다고 판단되시면 디엠 주십쇼 바로 어푸르브 하겠습니다!

2022-10-05 11:13 UTC, DomMorello commented on src/pages/FirstMissionPage.tsx
> +        <div aria-live="polite">{message}</div>
추가적으로 message를 보여주는 div 태그에 role="status" 를 주면 디폴트로 aria-live="polite", aria-atomic: true 값을 준다고 하네요! ㅎㅎ

자세한 내용은 [공식문서](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA22) 참고해주세요 :)

2022-10-05 12:31 UTC, lokba commented on package.json
> +    "file-loader": "^6.2.0",
와우 굉장히 꼼꼼하시네요 😎

2022-10-05 12:48 UTC, lokba commented on src/pages/FirstMissionPage.tsx
> +        <div aria-live="polite">{message}</div>
> 저는 개인적으로 polite 를 했을 때 조금 불편할거라고 생각해서 assertive를 줬습니다. 예를 들어, 아래 사진과 같이 긴 메세지를 읽고 있을 때 스크린리더 사용자가 승객을 추가하면 이 message를 통해 상태 변화를 알 수 있는데 저 긴 글을 다 읽은 후에 message를 읽어주니까 반응이 너무 느려서 답답할거라고 생각했습니다. 그냥 단순히 제 개인적인 생각입니다 :)

고민을 많이 하신 것 같네요. 긴 메세지의 경우에는 assertive가 적절할 수도 있겠네요. :) 


>추가적으로 message를 보여주는 div 태그에 role="status" 를 주면 디폴트로 aria-live="polite", aria-atomic: true 값을 준다고 하네요! ㅎㅎ

<img width="600" alt="스크린샷 2022-10-05 오후 9 46 05" src="https://user-images.githubusercontent.com/19251499/194063824-5a27737b-c93a-4cbc-a551-3f604adb7d53.png">
사진처럼 정말 default로 `aria-live="polite", aria-atomic: true`가 들어가있네요. 좋은 정보 감사합니다. 이왕 한번 적용해보겠습니다.

2022-10-05 12:50 UTC, lokba commented on package.json
> +    "build:refresh": "rm -rf build"
반영하였습니다. f3d6799

2022-10-05 12:51 UTC, lokba commented on package.json
> +    "file-loader": "^6.2.0",
반영하였습니다. 6724924

2022-10-05 13:04 UTC, lokba commented on src/components/PassengerCounter/PassengerCounter.tsx
> +        disabled={value === min}
돔하디의 생각 공유 감사합니다. 저도 다시 한번 생각하게 되네요ㅎㅎ

2022-10-06 05:36 UTC, merged

2022-10-06 05:37 UTC, DomMorello commented
수고 많으셨습니다!! ㅎㅎㅎㅎ

2022-10-07 02:57 UTC, kamwoo commented
모바일로 테스트할 때 최대 3까지 올린 다음에 포커스가 풀려요. 그래서 다시 heading부터 이동해야한다는 점에서 약간의 불편함을 느꼈습니다. 🙂 그 외에 사용하기에 이해도 잘됐고, 불편함 없이 사용할 수 있었습니다. 역시 록바👍