[항공사 웹사이트의 컴포넌트 접근성 높이기 - 1단계] 나인(장호영) 미션 제출합니다.
woowacourse/a11y-airline pull request #51
Opened 2022-10-06 03:05 UTC by jhy979

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

[Nine Airline](https://illustrious-travesseiro-f1eb42.netlify.app/)

## ✅ 요구사항 목록

**1 Spin Button**

- [x] 최대 인원수는 3명까지만 가능하게 구현합니다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [ ] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
성인 탑승자 한명 줄이기 버튼
성인 1 텍스트 숫자만 수정
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 2
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 3
```

**2 Carousel**

- [ ] 총 8개의 carousel 중 2개의 목록을 기본으로 보여준다.
- [ ] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [ ] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
1. 지금 떠나기 좋은 여행
2. 목록 8개 항목 포함 서울/인천 로스앤젤레스 일반석 왕복 1,481,800 대한민국 원 링크 목록 항목
3. 다음 버튼 (사용 중지)
4. 이전 버튼 (사용 중지)
```

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-10-07 02:32 UTC, yunjin-kim commented
아이폰 사파리, 구글 기준 화면이 깨지는 문제가 있습니다.
![IMG_4843](https://user-images.githubusercontent.com/79692272/194454710-4342600a-2845-4f89-b35f-af4a7d265221.PNG)

그리고 좌우로 슬라이드해서 버튼을 이동할 때 미상의 버튼도 잡히는 것도 고치면 좋을 것 같아요
![IMG_4844](https://user-images.githubusercontent.com/79692272/194455068-16ced778-1fc7-4f22-a381-64f7754f986b.PNG)

2022-10-07 02:39 UTC, rladpwl0512 commented
9 안녕하세요~ 미션 하시느라 수고 많으셨습니다! 
저는 아이폰 safari voiceover로 테스트해보았어요~ 
모두 잘 구현해주셨지만, 접근성 측면에서 아쉬운 부분만 남겨볼게요 😄 

- 화면이 깨지네요 🥲 (결 캡처본과 같습니다!) 
- 툴팁에 대한 설명이 필요할 것 같아요~ 현재는 물음표로 읽히고 있어요! 물음표 기호 태그에는 `aria-hidden`으로 스크린리더기가 읽지 않도록 해주고, 감싸고 있는 태그에 `aria-label`을 추가해서 툴팁버튼에 대한 설명을 해주면 어떨까요?
- 0명일 때, 3명일 때 버튼을 누르면 알림이 뜨면 좋을 것 같아요~!
- `-` 버튼 다음으로 넘어가면, 승객 상태를 읽어주는 것(성인 승객 추가 0)에 대한 것으로 넘어가네요 🥲 input창이나 +버튼으로넘어가면 좋을 것 같아요 😄

2022-10-07 08:25 UTC, jswith requested changes
하위 나인 🙌🙌

수업시간에 결, 위니가 남겨둔 리뷰가 있어서
나머지 부분에 대해서 몇가지 피드백 남겨드렸습니다~!
모든 걸 다 반영하실 필요는 없습니다!
필요한 부분 반영하시고 재리뷰요청 주시면 다시 확인하겠습니당!

테코톡 & 미션하시느라 고생하셨습니다!

2022-10-11 05:09 UTC, jhy979 commented
여러 브라우저 다 시도해봤는데 저는 크롬브라우저에서도 잘 보이네요.

근데... 사파리는 좀 다르네요 ㅠㅠ

2022-10-11 05:10 UTC, jhy979 commented on src/HelpTooltip/HelpTooltip.tsx
> +        </span>
네 맞아요. 그런데 돌이켜 생각해보니 수정해야겠어요..

버튼을 누르지도 않았는데 읽어주는 것이 이상하다고 생각이 드네요

[1764f2d](https://github.com/woowacourse/a11y-airline/pull/51/commits/1764f2d9eaaa47eee25f50ca54a8114cb515d5b0)

2022-10-11 05:10 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +        {`${passengerType} 승객 추가 ${inputValue}`}
ㅋㅋㅋ 마자요 polite 겸손하게 기다려주는 친구가 좋더라구요

2022-10-11 05:11 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +      </button>
아 마자요.. 보고 바로 다운받았는데

막상 구현할때 생각안하고 문자로 넣어버렸네요 ㅋㅋㅋ...

05e902516214f309f2536a0b8a60409a0065dc86

2022-10-11 05:12 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +        aria-label={`${passengerType} 탑승자 텍스트`}
흠... 이 부분은 어떻게 해야할지 감이 잘 안와요 ㅠ.ㅠ 어떤 의도로 말씀하신지 잘 몰겠어요😅

2022-10-11 05:13 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +        css={inputStyle}
오키... 인정해버렸습니다!!!

584186ce3e9c5f205ec1cdc2bf9db695b80eb471

2022-10-11 05:13 UTC, jhy979 commented on src/HelpTooltip/HelpTooltip.tsx
> +        role="tooltip"
오 버튼에 추가했어요!

추가하니깐 버튼 펼쳐짐 닫힘 이라는 안내 메시지를 읽어주네요!

2022-10-11 05:13 UTC, jhy979 commented on src/HelpTooltip/HelpTooltip.tsx
> +        role="tooltip"
위에서 적용했어요!

2022-10-11 05:14 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +        +
오 그 방법 신기방기한데요?

보이지 않게하고 그냥 내부의 값을 읽어주기!

2022-10-11 05:15 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +  };
인정!! 리뷰하면서 저도 이 부분은 반드시 적용해야겠다고 생각이 들었어요.

`사용 중지`라는 안내 메시지를 읽어주더라구요!

eccdb6a9a8e313c66e6134157cd6fde7234cf40f

2022-10-11 05:56 UTC, jswith commented on src/HelpTooltip/HelpTooltip.tsx
> +        </span>
👍🏻

2022-10-11 05:56 UTC, jswith commented on src/SpinButton/SpinButton.tsx
> +        {`${passengerType} 승객 추가 ${inputValue}`}
ㅋㅋㅋ 매너있는 친구죠

2022-10-11 05:56 UTC, jswith commented on src/SpinButton/SpinButton.tsx
> +      </button>
👍🏻

2022-10-11 05:57 UTC, jswith commented on src/SpinButton/SpinButton.tsx
> +        aria-label={`${passengerType} 탑승자 텍스트`}
`성인 탑승자 수`와 같은 label이 input을 나타내는 label로 더 적절하지 않을까? 하는 피드백이었어요 !

2022-10-11 05:58 UTC, jswith commented on src/SpinButton/SpinButton.tsx
> +  };
👍🏻

2022-10-11 05:58 UTC, jswith commented on src/SpinButton/SpinButton.tsx
> +        css={inputStyle}
👍🏻

2022-10-11 05:58 UTC, jswith commented on src/HelpTooltip/HelpTooltip.tsx
> +        role="tooltip"
👍🏻

2022-10-11 05:58 UTC, jswith commented on src/HelpTooltip/HelpTooltip.tsx
> +        role="tooltip"
👍🏻

2022-10-11 05:58 UTC, jswith commented on src/SpinButton/SpinButton.tsx
> +        +
👍🏻

2022-10-11 05:59 UTC, jhy979 commented on src/SpinButton/SpinButton.tsx
> +        css={inputStyle}
앗 이것도 있었꾼요?

2022-10-11 06:01 UTC, jswith approved these changes
스텝 1 미션하시느라 고생 많으셨습니다!

<img width="172" alt="스크린샷 2022-10-11 14 59 13" src="https://user-images.githubusercontent.com/64275588/195008421-ce43eae0-da6c-4347-87d3-ace194d35365.png">

승객 제한이 최대 3명인데 input에 직접 입력하는 경우에는 제한이 깨져버리는 문제가 있습니다!
오늘이 마감일이니 일단은 approve 하겠습니다! 이 부분은 step2 때 자유롭게 반영하시면 될 것 같아요 👍🏻

2022-10-11 06:01 UTC, merged