[항공사 웹사이트의 컴포넌트 접근성 높이기 - 1단계] 위니(김예지) 미션 제출합니다.
woowacourse/a11y-airline pull request #54
Opened 2022-10-06 06:08 UTC by rladpwl0512

👃🦷 안녕하세요~!!! 리뷰 잘 부탁드려요 :)
읽다가 수정이 필요하거나 이해안되는 부분이 있으면 바로 알려주세요~ 

## 🔥 결과
### 링크
[step1 링크](https://rladpwl0512.github.io/a11y-airline/)

### lighthouse
<img width="542" alt="스크린샷 2022-10-06 오후 3 07 54" src="https://user-images.githubusercontent.com/52344833/194227027-2a8bf895-ffe9-4b9d-8b43-33ac57530cc4.png">

## ✅ 요구사항 목록

**1 Spin Button**

- [x] 최대 인원수는 3명까지만 가능하게 구현합니다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
성인 승객 한명 줄이기 버튼
성인 1 텍스트 숫자만 수정 
성인 승객 한명 늘리기 버튼
성인 승객 현재 1명
성인 승객 한명 늘리기 버튼
성인 승객 현재 2명 
```

## 🧐 공유
- 최대한 시맨틱 태그를 사용하려고했습니다. 
시맨틱 태그를 사용하면 그 태그의 의미에 맞는 role과 aria 관련 속성들이 들어가있기 때문에, 웹 접근성에 더 좋습니다. 
기본적으로는 시맨틱 태그를 사용하되, 적절한 태그가 없는 경우 1) 그 태그의 역할에 맞는 role을 찾고 2) role에 기본적으로 적용되어있는 + 적용할 수 있는 aria 속성들을 확인 후 3) 알맞게 적용해주었습니다. 

- `aria-*` 속성이라고 해서 모든 role에 넣을 수 있는 것이 아니더라구요. role별로 적용해줄 수 있는 `aria-*` 속성을 잘 확인하고 설정해주어야할 것 같습니다! 
- 태그별로 적용할 수 있는 role도 따로 지정되어 있었습니다. 참고로, button 태그에 대한 mdn 설명입니다. 
  <img width="780" alt="스크린샷 2022-10-06 오후 4 41 33" src="https://user-images.githubusercontent.com/52344833/194246959-be563497-ea08-44aa-a464-a05e9bbc8879.png">

- `aria-label`, `aria-hidden`
기본적으로 <button> 과 같은 태그는 스크린리더기가 태그 내부에 있는 텍스트를 읽어줍니다. 하지만 우리 프로젝트 같은 경우, 버튼이 가지고있는 텍스트는 +, -, ? 와 같은 기호입니다. 스크린 리더기 사용자에게 이 기호 그대로 읽어주게 되면 의미를 파악하기 힘들 것입니다. 
따라서, 기호에는 은 `aria-hidden` 을 적용하여 스크린 리더기가 읽지 않도록 해주었고 버튼에 대해 스크린 리더기가 읽어줘야하는 설명을 `aria-label`에 적용해주었습니다. 아래는 코드에 적용한 예시 중 일부입니다. (- 버튼을 통해 성인 승객을 줄이는 버튼) 
  ```js
  <button
    className={
      count === 0
        ? "spin-button count-decrease disabled"
        : "spin-button count-decrease"
    }
    onClick={handleDecreaseCount}
    aria-label="성인 승객 한명 줄이기"
    >
    <span aria-hidden="true">-</span>
  </button>
  ```
  기본적으로 button에 `aria-label`을 설정해주지 않는다면 button 내부 텍스트를 읽어줍니다. 반대로 `aria-label`을 설정해준다면 사실 button 내부 텍스트인 -를 무시하고 aria-label을 읽어줍니다. 즉, 사실 내부 텍스트인 -에 대한 `aria-hidden` 설정은 필요가 없으나, 호환성을 위해 `aria-hidden="true"`를 명시적으로 넣어주었습니다. 스크린리더에 따라 내부 텍스트를 읽어줄 수도 있다고합니다~ 

- `display:none`, `visibility: hidden`은 스크린 리더기에서 읽지 못합니다. 
요소를 화면에서 보이지 않도록 해주는 `display:none`, `visibility: hidden`는 스크린 리더기에서 무시한다고 합니다. 그래서 화면에서 보이지는 않지만 스크린 리더기가 읽어줄 수 있도록 다음과 같은 css를 적용해주었습니다. invisible 클래스를 추가하여 사용할 수 있습니다. 
  ```css
  .invisible {
    position: absolute;
    width: 1px;
    height: 1px;
    clip: rect(0 0 0 0);
    margin: -1px;
    overflow: hidden;
  }
  ```

- 승객을 증가 및 감소시켜주었을 때, 승객 상태에 대한 설명을 실시간으로 해주었어야했습니다. ((0명인 상태) 성인 승객 한명 늘리기 버튼 - 성인 승객 현재 1명)
그래서 아래와 같이 승객의 수를 텍스트로 가지고있는 태그를 만들어주고, `aria-live` 를 통해 텍스트가 변경되면(승객 수가 변경되면) 스크린리더기가 이를 감지하여 읽어주도록 해주었습니다. 
  ```js
  <span
    role="status"
    className="passenger-count-input-state invisible"
    aria-live="polite"
  >
    성인 승객 현재 {count}명
  </span>
  ```
  처음에는 시맨틱 태그를 생각하다가, label을 떠올렸고 적용해주었습니다. 
  그런데 이 태그가 하는 역할을 다시 생각해보면 +, - 버튼을 클릭하면 -> input 텍스트 상태가 업데이트 된것에 대한 **알림** 이라고 생각이 되었습니다. label의 원래 역할과는 거리가 멀게 느껴져서, label에 이에 맞는 role이 있는지 찾아주었지만 label에는 role이 들어오는게 허용되지 않더라구요! 그래서 모든 role이 들어올 수 있는 span 태그를 사용하고, 의미에 맞는 [role="status"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/status_role)를 추가해주었습니다. role "status"는 사용자에게 상태에 대한 정보를 알려줄 때 사용하기때문에 적절하다고 생각했습니다. 
role="status"에는 aria-live=”polite”, aria-atomic=”true”가 기본적으로 지정되어있으나 [권고사항](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions#roles_with_implicit_live_region_attributes)을 보면, 높은 호환성을 위해 aria-live=”polite” 를= 지정해주라고 하고있기 때문에 추가해주었습니다. 

처음 하는 작업이라 생소했지만, 접근성에 대해 많이 생각해볼 수 있는 좋은 미션이였습니다~ 
부족한 부분 많이 피드백 해주세요! 🔥

2022-10-07 02:28 UTC, yunjin-kim commented
아이폰 사파리 기준으로 툴팁에서 소리가 나오면 좋을 것 같습니다

2022-10-07 02:29 UTC, jhy979 commented
하이 위니🙌

갤럭시 삼성 브라우저 기준으로 ? 버튼 클릭 시 툴팁이 켜지도록 구현되면 좋을 것 같네요!

alert 처리는 너무 좋았네요

2022-10-07 09:15 UTC, InKyoJeong requested changes
위니 안녕하세요~~ 위니랑 첫 미션을 같이했었는데 벌써 마지막 미션이라니 시간이 정말 빠르네요🤣 
예외처리도 잘 되어있고 깔끔하게 구현해주셨네요.
스크린리더에서도 잘 읽히네요!! 접근성에 대해 많이 생각하고 알아본게 느껴졌어요.
저도 리뷰하면서 많이 배웠습니다 ㅎㅎ

코멘트 달았는데 리더기에서 맨아래 숨긴 포커스가 잡히는 부분은 큰 이슈라고 생각되진 않아서 수정하셔도 되고 코멘트로만 말씀해주셔도 좋을것 같아요.

1단계 미션 고생하셨어요👍👍 주말 잘보내세용

2022-10-10 04:13 UTC, rladpwl0512 commented on src/components/PassengerCountInput/PassengerCountInput.css
> +}
보이지도 않고 focus도 되지 않지만, 스크린 리더가 읽어야 하는 경우인데요... 
이 문제를 고치기위해 정말 많은 시도를 했으나... 모두 실패했습니다 😱 
1. 수업시간에 하리가 공유해 준 내용 중, hidden=true로 두고 aria-hidden=false를 설정하면 된다는 이야기가 있었으나 실패했어요. 스크린리더마다 다른가봐요 🥲 
2. [요 페이지](https://mulder21c.github.io/2019/03/22/screen-hide-text/) 아래에 나오는 두가지 방법 모두 실패했습니다. 
3. [tailwind의 src-only css 설정값](https://tailwindcss.com/docs/screen-readers)들도 실패했습니다. 
4. tabIndex=-1 도 실패했습니다. 
5. 추측으로, aria-live가 content가 아닌 aria-label을 인식하도록 하면 되지 않을까? 라는 생각을 했었는데, ]aria-live는 aria-label을 무시](https://stackoverflow.com/questions/37733795/read-label-of-aria-live-region )한다고 하네요... 하하 실패했습니다. 추측 자체가 잘못됐어요! 
6. 그래서 pr을 샅샅이 뒤진 결과, [블링의 방식](https://github.com/woowacourse/a11y-airline/pull/29#discussion_r988906041 )을 채택했습니다. 일정 시간이 지나면 태그 내부 content가 비워지도록 만들어주었어요. 설정한 시간이 지나면 content가 비워지니까, focus가 되지 않습니다. 스크린 리더는 설정 시간 전에만 읽어주면 되니까, 넉넉히 5초로 잡아줬어요! 

---
[fix: 스크린리더에서 focus 되지 않도록 수정](https://github.com/woowacourse/a11y-airline/pull/54/commits/71fc9e058bc9c20eddb5b1c46abe977659cee978)

2022-10-10 04:16 UTC, rladpwl0512 reviewed
코이~ 꼼꼼한 리뷰 감사해요! 
리뷰 주셔서 많이 배울 수 있었어요 코이 최고~~~!!! 😎🔥
피드백 주신 부분 수정하고, 코멘트에 수정 과정을 담았으니 확인해주세요! 

잘부탁합니다 ~!!!

2022-10-10 07:51 UTC, InKyoJeong commented on src/components/PassengerCountInput/PassengerCountInput.css
> +}
비워주는방법 좋네요 👍

2022-10-10 07:56 UTC, InKyoJeong approved these changes
위니 정말 수고했어요!! 머지하겠습니당 ㅎㅎ

2022-10-10 07:56 UTC, merged