[항공사 웹사이트의 컴포넌트 접근성 높이기 - 1단계] 무비(변영화) 미션 제출합니다.
woowacourse/a11y-airline pull request #59
Opened 2022-10-06 08:47 UTC by byhhh2

안녕하세요 도리🐠❤️ !!
도리가 리뷰어라니!!! 심장이 두근두근대서 어쩔 도리가 없네용 ㅋㅋ 😆
시간 안에 최대한 열심히 하려고 해봤습니다!! 
부족한 코드지만 차근차근 업그레이드하겠습니다 👏

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

[링크 🛫](https://byhhh2.github.io/a11y-airline/)

- 스크린리더 환경 : 맥 보이스오버 
- 브라우저 환경 : 크롬 

기준으로 작성했습니다 🙂

## ✅ 요구사항 목록

**1 Spin Button**

- [x] 최대 인원수는 3명까지만 가능하게 구현합니다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
성인 탑승자 한명 줄이기 버튼
성인 1 텍스트 숫자만 수정
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 2
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 3
```

```
voiceover 설명

airline 
승객 선택을 위한 서비스, main 
승객 선택, h1
성인 탑승자 수를 고릅니다., form 
성인 기준 상세 안내, tooltip
성인 탑승자 한명 줄이기 버튼
성인 탑승자 수 입력칸
성인 탑승자 한명 늘리기 버튼
```

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

## 🙂 시도해본 것 

### 👋 작업 사항 

- 스크린리더가 읽을 수 있게 하기
  - 승객 선택에 대한 설명을 태그 순차적으로 읽게 하기 
  - 승객수 증감을 했을 때 설명 읽어주기 
- 시맨틱 태그 활용하기 
- 메타데이터 추가하기
- tab으로 쉽게 접근할 수 있도록 하기 
- 툴팁이 사용자가 원할 때만 설명할 수 있도록 하기 

### 👋 aria-*

#### aria-label

- 모든 HTML 태그에 사용할 수 있다.
- 대체 텍스트 역할을 한다. 

#### aria-labelledby

- 현재 요소를 설명할 텍스트가 있을 경우 그 텍스트와 현재 요소를 연결하기 위해 사용 

#### aria-live

- 실시간으로 내용을 갱신하는 영역
    - `polite` : 중요도가 낮은 내용, 현재 진행중인 음성을 방해하지 않는다.
    - `assertive` : 중요도가 높은 내용, 갱신 내용을 즉시 사용자에게 전달
- 탑승자 수가 증감할 때 값을 실시간으로 전달하기 위해 사용

#### aria-hidden

- 접근성 트리에서 해당 요소와 모든 자식이 제거된다. 
- 장식적인 콘텐츠 (아이콘, 텍스트)를 숨기면 된다.
- 예를 들어 툴팁에서의 `?` 장식 텍스트를 숨기면 된다. 

#### aria-expanded

- 웹 접근성 측면에서 열린 부분은 true, 닫힌 부분은 false

<br>

### 👋 사용을 편하게 해주는 아이들

#### tabIndex

- 요소가 포커스 가능함을 나타낸다.
- 주로 tab 키를 사용하는 연속적인 키보드 탐색에서 어느 순서에 위치할지 결정
- tabIndex=”-1”
    - 연속 키보드 탐색으로 접근할 수 없으나 JS나 시각적으로는 포커스가 가능함을 의미한다. (보통 위젯의 접근성 확보를 위해 사용한다.)
    - 즉, 포커스는 가능하지만 탭 순서에서 제외된다.
    - 승객 선택 컴포넌트에 바로 접근했으면 좋겠지만, tab으로는 접근하지 않았으면 좋겠어서 승객 선택 컴포넌트에 tabIndex=”-1”을 걸어주었다.
- 0보다 큰 tabIndex는 피해야한다. (보조기술의 페이지 탐색, 조작에 방해가 될 수 있음. 그러므로 요소 순서를 논리적인 순서대로 배치할 것)

> **대화형 컨텐츠 vs 비대화형 컨텐츠** 
> 
> - 대화형 컨텐츠 : 사용자와 상호작용을 위해 특별하게 설계된 요소
> (input, a, button 등의 태그)
> - 비대화형 컨텐츠 : 이외
>

#### [텍스트 숨김 관련 참고한 글](https://mulder21c.github.io/2019/03/22/screen-hide-text/)

#### role=*

- role="dialog"
  - 사용자의 인터렉션이 필요한 현재 문서의 하위창 표시 
  - 이번 미션에서는 승객 선택창인 것 같아서 표기해주었습니당.

<br>

### 👋 시맨틱 태그 

- 검색엔진은 태그를 기반으로 페이지 내 검색 키워드의 우선 순위를 판단 (SEO)
- 스크린 리더를 사용하여 페이지를 탐색할 때 도움이 된다.
- 태그는 채워질 데이터를 기반으로 결정해야 한다. 

> - main : 지배적인 콘텐츠 영역을 나타내는 태그
> - header : 머리말 영역
>    - 문서 전체의 header 일 수도 있고, 특정 영역인 section의 header일 수도 있다.
>    - header 부분에 제목 태그가 올 수 있다. (h1, h2 .. )
> - section : 문서에서 독립적인 영역
>    - 제목이 있는 것이 일반적이다.
>    - header, section, footer 3가지로 나누었을 때 section은 본문 컨텐츠를 담는다.
> - article : 그 자체로 의미가 있는 웹 사이트의 부분
>    - 예시 : 게시물, 기사, 블로그 작성글, 대화형 위젯 등
>    - section 안 실질적인 내용 (section : 뉴스 분류, article : 기사 내용)
> - abbr : 줄임말 또는 머리 글자를 나타낸다. (툴팁의 ?)
>    - title 속성을 이용하면 전체 뜻이나 설명을 제공할 수 있다.
> - p : 글의 단락(글의 작은 덩어리)을 나타낸다.

<br>

### 👋 메타 데이터

- description : 웹 페이지의 요약 정보 제공

이 정도만 적용한 것 같습니다 !!

## 🙂 고민

- 스크린 리더가 특정 내용을 읽지 않도록 해주고 싶은데 🤔 제가 시간이 부족해서 급하게 찾았더니 잘 안나오더라구요 흑흑 ~~ `aria-hidden`말고 어떤 방법이 있나요 리뷰어님!?! 도와주세요 🥺
- `tooltip`에 접근성을 좀 더 부여할 수 있는 방법은 어떤게 있을까요?! 
- `input type="number"`에서 `min`, `max`가 텍스트를 직접 수정하면 먹질 않더라구요 ... 🥲 (차암나) 그래서 util을 직접 만들어 주었는데 더 좋은 방법은 없을까요 엉엉
- 보이스 오버..는 도대체 왜 콘솔까지 읽는 걸까요? 그건 안 읽어도 되는데..

2022-10-07 13:06 UTC, prefer2 requested changes
뭅이뭅이 🎥❤️ 무비의 꼼꼼한 PR과 코드를 보며 감동의 도리도리를 하게 된 도리입니다.
컴포넌트 꼼꼼하게 분리해주시고 멋져! 스토리북은 정말 감동이었습니다(보이스오버 목소리를 들으며 스토리북에서 접근성 테스트가 가능하다면 정말 좋겠다라는 생각을 했습니다ㅋㅋ)

> 스크린 리더가 특정 내용을 읽지 않도록 해주고 싶은데 🤔 제가 시간이 부족해서 급하게 찾았더니 잘 안나오더라구요 흑흑 ~~ aria-hidden말고 어떤 방법이 있나요 리뷰어님!?! 도와주세요 🥺

저도 aria-hidden 정도밖에 모르겠네요ㅠ 도움이 되지 못해서 미안합니다 뭅이. 혹시 새롭게 알게 된다면 저에게도 공유해주시겠사와요??

> tooltip에 접근성을 좀 더 부여할 수 있는 방법은 어떤게 있을까요?!

아이폰-사파리 환경으로 시도해보았을 때 아래 동영상과 같이 동작하고 있어요. 내부 내용으로 접근이 안되고 있는데 내부 내용을 알 수 있다면 접근성이 더 좋아질 것 같아요!

https://user-images.githubusercontent.com/67692759/194558394-569bd1b1-0ca6-4a3c-9d94-e1ae3f21eb9a.MP4



> input type="number"에서 min, max가 텍스트를 직접 수정하면 먹질 않더라구요 ... 🥲 (차암나) 그래서 util을 직접 만들어 주었는데 더 좋은 방법은 없을까요 엉엉

직접 입력은 어쩔 수 없는 것 같아요 🥲 값을 확인하고 범위 값이 아니면 경고 메시지를 보여주거나 입력이 안되게 하는 수 밖에 없을 것 같아여. 지금 값을 직접 수정하고자하면 0값이 없어지지 않고 있어서 이 부분 한 번 다시 봐주시면 좋을 것 같아요

![스크린샷 2022-10-07 오후 9 31 16](https://user-images.githubusercontent.com/67692759/194553907-40d1a851-6dbe-4bf6-98bb-bbff96e29723.png)

> 보이스 오버..는 도대체 왜 콘솔까지 읽는 걸까요? 그건 안 읽어도 되는데..

혹시 개발자인 분들을 위해서 아닐까라는 추측만 하게 되네요 🤔

미션하느라고 수고 많으셨어요! 무비 pr보면서 저도 공부 많이 했네요!! 최고!!

2022-10-11 05:01 UTC, byhhh2 commented on package.json
> +    "@storybook/testing-library": "^0.0.13",
도리의 발톱 정도랄까? 🐤

2022-10-11 05:10 UTC, byhhh2 commented on package.json
> +    "prop-types": "^15.8.1",
맞습니다 ! CRA를 통해 기본 설정을 진행했고, 접근성 미션에만 집중했기 때문에 패키지 부분은 신경써주지 않았습니다.ㅎㅎ

하~지만 리뷰어님 말씀이라면 🥺✨ 반영해야죠 ~!! 
사용하지 않는 패키지를 전체적으로 삭제해주었습니다.!! >_<

[`aff652e`](https://github.com/woowacourse/a11y-airline/pull/59/commits/aff652e1bd19603a73c11fdd0c25d2a02afde207)

2022-10-11 05:11 UTC, byhhh2 commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
이런!!!!!!!!!!!!
RTL까지는 도입하지 않을 것 같습니당 ㅎㅎ.
바로.. 삭.제 🔪

[`aff652e`](https://github.com/woowacourse/a11y-airline/pull/59/commits/aff652e1bd19603a73c11fdd0c25d2a02afde207)

2022-10-11 05:15 UTC, byhhh2 commented on src/reportWebVitals.ts
> +      getTTFB(onPerfEntry);
저도 [페이먼츠 미션](https://github.com/woowacourse/react-payments/pull/98#discussion_r864413978)때 알았어요!! ㅎㅎ 
단순히 console.log만 넣어주면 콘솔에 측정 내용이 찍히니깐 편하더라구요 🥺
lighthouse가 좀 시간이 걸리고 기다려야 한다는 점이 아쉽지만,, 그래도 시각적으로는 훨씬 편하긴 했어용

2022-10-11 05:22 UTC, byhhh2 commented on src/index.tsx
> +reportWebVitals();
이번 미션에는 딱히 사용하지는 않았지만! 
측정이 필요할 때를 대비해서 남겨두는 게 좋을 것 같아요!!
하지만 주석은 지워주는 것이 좋겠네요 ㅎㅎ 
고민해보니 🤔 한글 주석으로 변경하는 것도 나쁘지 않은 것 같은데 리뷰어님은 어떻게 생각하시나요 ?! 

[`6214d0e`](https://github.com/woowacourse/a11y-airline/pull/59/commits/6214d0ed56afd226ad37fc8ab65e390b3e942074)

2022-10-11 05:25 UTC, byhhh2 commented on src/components/Counter/index.tsx
> +        <S.Title aria-hidden>{title}</S.Title>
현재 성인 승객 선택 form에 도착하면 `성인 탑승자 수를 고릅니다., form `이라고 안내 문구를 줍니다!
이런 이유로 title까지 읽을 필요가 없다고 생각해서 `성인`을 읽지 않도록 설정해주었습니당 🙂

2022-10-11 13:53 UTC, byhhh2 commented on src/components/Tooltip/index.tsx
> +        <S.Tooltip aria-hidden>?</S.Tooltip>
저는 사용자가 원할 때만 툴팁 내용을 읽어주는 게 옳다고 생각합니다!!! 
그래서 저는 이를 기준으로 구현했는데요.. 몇시간 고민해도 쉽지가 않네요 ㅠㅠ 

우선 제 코드는 

- 툴팁이 button 같은 대화형 컨텐츠는 아니지만 tabIndex 0을 주어 탭으로 접근이 가능하다.
- 사용자가 탭으로 focus하거나, 마우스를 hover 했을 경우에만 툴팁 안 content를 읽어준다. (국제선 만 12세 이상, 국내선 만 13세 이상)
- 만약 focus되어 있지 않다면 처음 웹 페이지 설명에서 어떤 툴팁(name)인지 알려준다. (성인 기준 상세 안내)

근데..! 제 코드에 문제점은 ㅠㅠ

`aria-live="assertive"`속성을 가진 hidden p 태그를 label처럼 사용했기 때문에 

```jsx
<VoiceText aria-live="assertive">{isHover ? content : name}</VoiceText>
```

처음 웹 페이지 설명에서 툴팁에 관련된 설명인지 확인할 수가 없습니다. 
또, 이를 사용해서 aria-expanded 속성을 달아주는 것도 애매해져버렸어요....

이 문제를 해결하려고 여러 방면을..생각해봤는데 해결하지 못했네요 🥲

2022-10-11 13:58 UTC, byhhh2 commented on src/components/VoiceLabel/index.tsx
> +    <S.Container htmlFor={targetId} aria-live={ariaLive}>
도리 정보 공유 너무 감사합니당 !!! >_< 
role="status"는 aria-live="polite" 속성과 aria-atomic="true"을 합친거군요!

2022-10-11 14:32 UTC, byhhh2 commented
안녕하세요 도리 ! 제가 피드백 반영이 좀 늦었네요 🥲,,! 
(사실 merge 마감일자를 착각하고 있었어요 ㅎ..)
그래서 부랴부랴 시작한 탓에 .. + 툴팁에 집착한 탓에..
많은 부분을 고치지 못했는데요 🤪 (긁적..) 

우선 제 문제상황은 

- 사파리에서 툴팁에 접근하지 못하는 문제 

=> 이는 아이폰-사파리에서 tabIndex를 지원하지 않기 때문이군요 ㅠㅠ 슬픕니다 슬퍼요,,
여러 방면에서 고민해봤는데 명확한 해결을 내리지 못했어요..혼자 고민하니깐 더더욱 모르겠네요 ㅠㅠ 이건 추후에 리뷰어님이나 다른 크루들에게 물어보고 수정해야할 것 같습니다..

- 직접 입력시 기존 숫자인 0이 지워지지 않는 현상

0이 이미 입력되어 있고, 뒤에 1을 입력했을 때 01이 되어버리는 이유는 count state문제가 아니라 input value가 꼬이는게 문제내요..
고민해도 예쁘게 해결할 방법이..진짜 안떠오르네요.. 뭔가 간단해 보이는데 어..째서..? 
하아.. 너무 슬프네요 슬퍼..😵‍💫 (너무 모......르.......겠..어요..)


우선 이 둘 빼고는 피드백 반영한 것 같습니다!!
도리 꼼꼼한 리뷰 너무 감사하고, 공유해주신 자료도 너무 도움됐어요 :) 
(무비는 행복해요) 
땡큐 도리 ~ ❤️

2022-10-11 15:07 UTC, merged