[항공사 웹사이트의 컴포넌트 접근성 높이기 - 1단계] 콤피(류현승) 미션 제출합니다.
woowacourse/a11y-airline pull request #60
Opened 2022-10-06 08:53 UTC by compy-ryu

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

[링크](https://compy-ryu.github.io/a11y-airline/)

## ✅ 요구사항 목록

**1 Spin Button**

- [x] 최대 인원수는 3명까지만 가능하게 구현합니다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
성인 탑승자 한명 줄이기 버튼
성인 1 텍스트 숫자만 수정
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 2
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 3
```

**2 Carousel**

- [ ] 총 8개의 carousel 중 2개의 목록을 기본으로 보여준다.
- [ ] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [ ] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
1. 지금 떠나기 좋은 여행
2. 목록 8개 항목 포함 서울/인천 로스앤젤레스 일반석 왕복 1,481,800 대한민국 원 링크 목록 항목
3. 다음 버튼 (사용 중지)
4. 이전 버튼 (사용 중지)
```

## 🧐 공유

반가워요! 티거 티거 🐯
PR 작성이 늦어져서 죄송해요ㅎㅎ;; 요즘 정신이 없어서 그만..

아무튼! (전)페어에서 리뷰어로 만나니까 반갑네유 ㅋㅋㅋ
이번 미션에서는 아래와 같이 시도해보았습니다!
* 시멘틱 태그 사용하기
* aria 속성 사용해보기
* 모바일에서 스크린 리더 사용하여 직접 테스트해보기

혹시 부족한 점 있다면 말씀주시면 적극적으로 반영해가도록 하겠습니다!
감사합니다!!

2022-10-06 11:24 UTC, daaaayeah commented
콤피 안녕하세요~! PR 코멘트 작성이 완료되면 리뷰를 시작하려고 하니 작성 후에 한번 더 알림 부탁드려요 🦖

2022-10-07 02:52 UTC, kwannee commented
1. 유저 동작의 결과를 알려주는 announce가 있으면 좋을 것 같습니다.
2. tooltip이 모바일 환경에서 읽히지 않는 오류를 해결하면 좋을 것 같습니다.

2022-10-07 02:54 UTC, compy-ryu commented
## 수업 시간 피드백 (후이, 동키콩, 콤피)
- 유저 동작 결과에 대한 내용에 대해서도 스크린 리더에 알려주기
- 모바일 스크린 리더에서 툴팁이 작동되지 않는 문제 해결하기
- 모바일 스크린 리더 조작 중 화면이 드래그 될 시 불편하다. 버튼과 같은 영역은 드래그 막기

2022-10-08 13:03 UTC, daaaayeah requested changes
## 🐯💬

콤-하 🦖 리뷰어로 찾아온 티거입니다
좋은 주말 보내고 계시나요~?

> (전)페어에서 리뷰어로 만나니까 반갑네유 ㅋㅋㅋ

콤피와 페어하던 기억이 새록새록... 꽤 오래됐네요 🥲
저도 반갑습니다 호호 어제도 반가웠고요~!

> 이번 미션에서는 아래와 같이 시도해보았습니다!
> 
> - 시멘틱 태그 사용하기
> - aria 속성 사용해보기
> - 모바일에서 스크린 리더 사용하여 직접 테스트해보기

이야 미션 중에도 모바일 테스트를 직접 하셨군요!
여러 환경에서 테스트를 하셨다니 대단하십니다 👍🏻

콤피 이번 미션도 고셩하셨어요~!
아래에 반영되었으면 하는 접근성 관련 개선점을 따로 정리하였으니 확인 부탁드려요 🦖

## 개선점

### 1. 사용자 액션에 대한 피드백

후이가 남겨주신 코멘트에 전적으로 동의합니다

> 1. 유저 동작의 결과를 알려주는 announce가 있으면 좋을 것 같습니다.

사용자가 자신의 액션(버튼으로 승객 수 조절)에 대한 피드백을 받지 못하고 있네요.
이 부분은 꼭 반영해 보시는 게 접근성 공부에 좋다고 생각해요 🙂

> 2. tooltip이 모바일 환경에서 읽히지 않는 오류를 해결하면 좋을 것 같습니다.

크롬 브라우저와 맥북 보이스오버 환경에서도 tooltip에 접근하는 방법이 없는 것 같은데 맞나요?!
이 부분도 확인 한번 부탁드립니다

### 2. 승객 수 제한 안내

승객 수가 최대 3명으로 제한되어 있는 것에 대한 안내가 필요하다고 생각합니다
좀 더 나은 콤피항공의 접근성을 위해 ✨

2022-10-11 04:05 UTC, compy-ryu commented on src/components/ToolTip/ToolTip.tsx
> +  })
styled components를 쓰면 좀 더 편했겠지만...
저는 코드와 스타일 시트가 완전히 분리되어있는걸 선호해서 작은 프로젝트에서는 sass를 쓰고있어유!

2022-10-11 05:52 UTC, compy-ryu commented on postcss.config.js
> +    autoprefixer: {},
css browser [vendor prefix](https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix)를 자동으로 붙여주는 plugin입니더!

현재 사용 중인 sass & css에서는 styled component와 다르게 browser vendor prefix를 자동으로 붙여주지 않아서 postcss의 autoprefixer 플러그인을 활용해서 하나만 입력하더라도 모두 자동으로 붙여줄 수 있도록 처리해두었어요!

2022-10-11 05:52 UTC, compy-ryu commented on src/components/ToolTip/ToolTip.tsx
> +}
사용 중단을 권장하는 옵션이였군유...😱

사용한 이유는 함수의 매개변수에 기본 값을 입력하니 코드가 정돈되지 않는 느낌이 강해서
defaultProps를 활용해서 하단에 따로 명시해주었었어요!

프로젝트에서도 제거해야겠군요 ㅠㅠ

2022-10-11 05:53 UTC, compy-ryu commented on src/components/ToolTip/ToolTip.tsx
> +  })
styled components를 쓰면 좀 더 편했겠지만...
저는 코드와 스타일 시트가 완전히 분리되어있는걸 선호해서 작은 프로젝트에서는 sass를 쓰고있어유!

2022-10-11 05:55 UTC, compy-ryu commented on src/components/Counter/Counter.tsx
> +}
반영했습니다!

* 75de41b5435ad34afbe6aae4c5d52d2adb14671a

2022-10-11 05:56 UTC, compy-ryu commented on .gitignore
> +build
으어어 이게 왜 이렇게 되있쥬ㅎㅎㅎㅎ;;;;;
고쳤습니더!

* 64d12952b046e0ef3155a91591f0fbdfc26477cc

2022-10-11 05:58 UTC, compy-ryu commented on src/components/ToolTip/ToolTip.tsx
> +    <div className={cn(styles.componentTooltip, className)} aria-hidden="true">
툴팁 영역이 버튼과 겹쳐져 해결하기 위해 넣었었습니다..
다른 방식으로 개선해보았어요!

* 8598b30c6aceb4cb3d7266c280cca7e8c30a1049

2022-10-11 06:01 UTC, compy-ryu commented
티거 자세한 피드백 감사해요!
남겨주신 리뷰 모두 반영 완료했고, 편하실 때 리뷰 부탁드릴께요!

1. 사용자 액션에 대한 피드백
=> cb4a2b5b83e3a0d8ac8ee1290e3380f2cca7dfea

2. tooltip이 모바일 환경에서 읽히지 않는 오류를 해결하면 좋을 것 같습니다.
=> 8598b30c6aceb4cb3d7266c280cca7e8c30a1049

2. 승객 수 제한 안내
=> 이 부분은 툴팁 영역이 읽어지도록 개선 + 액션에 대한 피드백 개선이 적용되면서 해결된 부분이라 생각해서 추가적으로 개선하진 않았습니다!

2022-10-11 06:48 UTC, daaaayeah approved these changes
콤피 연휴 잘 보내고 오셨나요 🦖

코멘트와 코드 모두 확인했습니다
리뷰에 꼼꼼하게 피드백해 주셔서 감사합니다 👍🏻

그런데 툴팁에 접근하면 아래와 같이 툴팁 메시지를 두 번 읽어주네요 😮
맥 보이스오버, 크롬 환경입니다

<img width="646" alt="스크린샷 2022-10-11 15 32 29" src="https://user-images.githubusercontent.com/52729559/195013878-f786f32d-136b-41e0-9109-b83cb791af2c.png">
<img width="646" alt="스크린샷 2022-10-11 15 32 55" src="https://user-images.githubusercontent.com/52729559/195013918-3330396a-9abc-4bd7-87fa-e44997746d68.png">

마감 기한이 다가오고 있으니 수정하고 싶으시다면 2단계 때 함께 수정하면 좋을 것 같습니다
머지할게요 🚀 이번 미션 고생하셨어요~!

2022-10-11 06:49 UTC, merged