[항공사 웹사이트의 컴포넌트 접근성 높이기 - 2단계] 돔하디(이동현) 미션 제출합니다.
woowacourse/a11y-airline pull request #70
Opened 2022-10-12 11:54 UTC by DomMorello

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

## [배포 링크](https://stately-horse-158215.netlify.app/)

## ✅ 요구사항
**2 Carousel**

- [x] 총 8개의 carousel 중 2개의 목록을 기본으로 보여준다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
1. 지금 떠나기 좋은 여행
2. 목록 8개 항목 포함 서울/인천 로스앤젤레스 일반석 왕복 1,481,800 대한민국 원 링크 목록 항목
3. 다음 버튼 (사용 중지)
4. 이전 버튼 (사용 중지)
```

## 🧐 공유
> 안녕하세요 무비 :) 이렇게 다시 만나니 반갑습니다!
1단계 미션에서 아주 예리한 지적들을 많이 해줬는데 이번 2단계에서도 예리한 지적과 피드백 기대하겠습니다 ㅎㅎㅎ
구현하면서 고민했던 내용들 간단하게 아래 남기겠습니다. 코드리뷰할 때 참고해주세요 :)

### Carousel UI HTML
대한항공 구현 방식을 참고하면서 구현했습니다.

우선 **`<ul>` 태그를 활용해서 리스트를 출력**했습니다. 이렇게 구현했을 때 스크린리더가 친절하게 목록에 들어가는 것을 알려주고 몇 개의 목록이 있는지까지, 목록의 끝도 알려줌으로써 사용자에게 더 나은 경험을 제공하는 것 같습니다!

### Carousel Button
이전과 다음 버튼을 스크린 리더 사용자에게도 알려주기 위해서 **내부에 span 태그로 텍스트를 작성**했습니다. css 를 통해서 화면에는 보여주지 않게 구현했습니다.

고민했던 내용 중에 하나가 disabled 를 어떻게 할 지였는데, 처음에는 더이상 이전으로 넘어갈 수 없거나 이후로 넘어갈 수 없을 경우 disabled 속성을 줬습니다. 그런데 이렇게 했을 때 탭으로 접근할 수가 없기 때문에 스크린리더 사용자한테는 다소 불편할 수 있다고 생각했습니다. 대한항공 같은 경우는 버튼이 비활성화돼도 접근할 수 있고 비활성화됐다고 알려주는 부분을 참고해서 **`aria-disabled` 속성을 활용**했습니다.

이 속성을 사용하면 접근이 가능하고 스크린리더가 비활성화된 상태임을 읽어줍니다. 하지만 이렇게 했을 경우 동작하지 않아야 할 이벤트 핸들러가 동작하는 것까지는 막을 수 없었습니다. 그래서 **함수 내부에서 해당 코드가 disabled 되는 상황에서는 동작하지 않도록 예외 처리**를 해줬습니다.

### Carousel 구현
접근성과는 관계 없지만 새로운 기능을 구현해봐서 좋은 공부가 됐습니다. HTMLElement 의 스크롤 속성을 통해 스크롤을 이동시키거나 현재 스크롤의 위치, 스크롤 넓이 등을 활용할 수 있습니다. 이런 **속성(`scrollLeft`)을 활용해서 버튼 클릭시 리스트의 넓이만큼 이동할 수 있도록 구현**했습니다.

하지만 이렇게 하는 경우 탭으로 스크롤이 넘어가는 경우를 캐치하지 못해서 버튼의 비활성화 시점에 정확하게 버튼의 상태를 변화시킬 수 없는 버그가 있었습니다.

예를 들어, 버튼이 아닌 탭을 통해 마지막 아이템까지 포커스하면 스크롤이 마지막으로 이동하게 되는데 그 때 이전 버튼으로 탭으로 포커스를 이동하면 비활성화됨 이라고 스크린 리더가 읽는 상황이 있었습니다.

이런 부분을 해소하기 위해 버튼 **이벤트 핸들러에서는 스크롤을 이동만 시켜주고 스크롤 이벤트가 발생했을 때 버튼의 disable 판단을 해서 상태를 변화**시켜줬습니다. 이 과정에서 스크롤 이벤트이다 보니 디바운스 함수를 활용해서 최적화를 해줘야 하는 상황이 생겨서 **debounce를 활용**했습니다.

2022-10-14 02:15 UTC, kamwoo commented
- [x] 캐로우셀 이미지 영역 안에서 더블 탭을 통해 링크를 이동할 수 있어야 합니다.
- [x] 보이스오버 기능을 이용해 캐로우셀을 넘길 때 포커싱 되는 이미지가 활성화된 영역에서 잘 보이는지 체크합니다.
- [x] carousel 안의 이미지 영역에서 정보를 의미를 드러내서 알려주는지 체크합니다.
- [ ] 예) 금액 정보를 의미를 잘 드러내면서 알려주는지 체크합니다. (실제로는 1,157,500 대한민국원 으로 한국 금액임을 쉽게 알려줄 수 있습니다. OS별 보이스오버에 따라 다를 수는 있음)
- [ ] 캐로우셀의 다음 버튼을 이용해 마지막 이미지까지 이동하고 나면, 더이상 이동할 수 없다는 것을 알려줘야 합니다.
- [x] 캐로우셀 이미지를 끝까지 본 이후에 이전 버튼을 이용해 캐로우셀의 맨 앞으로 이동할 수 있어야 합니다.
- [ ] 마찬가지로 이전 버튼이 맨 앞까지 이동하고 나면, 더이상 이동할 수 없다는 것을 알려줘야 합니다.
- [x] 스와이프 이동과는 별개로 이미지를 선택했을 때 해당 캐로우셀 이미지에 대한 정보를 포커싱할 수 있어야 합니다.

2022-10-14 02:19 UTC, wonsss commented
## KRW 등
모바일에서는 대한민국 원으로 읽진 않고,KRW로 읽힘. 그런데 문제는 한 요소의 관련 텍스트들을 띄어쓰기 단위로 다 끊어서 읽게 돼서 그런 것 같아요

## 캐로우셀의 다음 버튼을 이용해 마지막 이미지까지 이동하고 나면, 더이상 이동할 수 없다는 것을 알려줘야 합니다.

'비활성됨' 이라고는 읽어줘서 괜찮은 것 같아요. 다만 요구사항에서 '다음 사용중지' 와 같이 사용중지까지 읽어주라고 했던 것 같아서 확인해주시면 좋을 것 같아요

## 마찬가지로 이전 버튼이 맨 앞까지 이동하고 나면, 더이상 이동할 수 없다는 것을 알려줘야 합니다.
모바일에서는 읽어주지 않는 것 같아요

2022-10-14 13:37 UTC, byhhh2 requested changes
안녕하세요 하디 ~~~ 다시 만나니 더 만갑네요 ^^
(이거 쓰고 있는데 한숨을 너무 깊게 쉬셔서 리뷰하기 죄송스럽 ^^.. 땅꺼지겠어오)

<img width="150" src="https://user-images.githubusercontent.com/52737532/195860268-b64396bc-2e17-4c38-9f58-8ed1bc02ffd9.png" />


잘 구현해주셨네요! 
다른 분들이 남겨주신 리뷰는 중복될 것 같아 남기지 않고, 다른 부분만 남기겠습니다.!

> 우선 **`<ul>` 태그를 활용해서 리스트를 출력**했습니다. 이렇게 구현했을 때 스크린리더가 친절하게 목록에 들어가는 것을 알려주고 몇 개의 목록이 있는지까지, 목록의 끝도 알려줌으로써 사용자에게 더 나은 경험을 제공하는 것 같습니다!
> 

맞아요! 저도 `ul`, `li`, `a` 태그를 쓰니 접근성이 잘 지켜지더라구요! 
역시 상황에 맞는 태그를 사용하는 게 중요한 것 같습니다 🙂

> 이전과 다음 버튼을 스크린 리더 사용자에게도 알려주기 위해서 **내부에 span 태그로 텍스트를 작성**했습니다. css 를 통해서 화면에는 보여주지 않게 구현했습니다.
> 

오,, `aria-label`은 고려하지 않으셨나용?

> 버튼이 비활성화돼도 접근할 수 있고 비활성화됐다고 알려주는 부분을 참고해서 **`aria-disabled` 속성을 활용**
> 

꿀팁 감사해요 👍 저도 잘 써먹었습니다 ㅎㅅㅎ

> 이 과정에서 스크롤 이벤트이다 보니 디바운스 함수를 활용해서 최적화를 해줘야 하는 상황이 생겨서 **debounce를 활용**했습니다.
> 

와우,, 접근성 미션에 성능까지 챙기시다니.. 대단쓰 👍

> 아이템에 마우스를 hover 했을 때 테두리가 변경되고 버튼에도 hover시에 outline이 생기도록 함으로써 스크린 리더 사용자가 아닌 이용자를 위해서도 접근성에 신경썼습니다 :)
> 

ㄷㄷ 역시 괴물 개발자 🧔🏽‍♂️ 대한항공 입사해도 되겠어요

### 추가

focus된 element가 화면에 보이지 않는 것은 좀 아쉽네요! 
전 [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)를 통해 해결했어요!!

<img width="583" alt="스크린샷 2022-10-14 오후 10 09 01" src="https://user-images.githubusercontent.com/52737532/195977467-6f0f034c-0c0c-4fc0-9fbe-a0da806f621b.png">


<br>
<br>

> 수고하셨습니다!

2022-10-14 13:37 UTC, byhhh2 commented on src/pages/HomePage/index.tsx
> +      scrollContainer.current.scrollLeft >= (itemWidth + itemMargin) * 5;
```
scrollWidth <= offsetWidth + scrollLeft
```

이 식을 활용하면 `5`를 명시하지 않아도 될 것 같습니다 : )

2022-10-14 13:37 UTC, byhhh2 commented on src/pages/HomePage/index.tsx
> +      scrollContainer.current.scrollLeft += itemWidth + itemMargin;
좋네요 👍

[`scrollBy`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy)를 활용하면 좀 더 선언적으로 해결할 수 있어요 !

2022-10-14 13:37 UTC, byhhh2 commented on src/component/TravelCard/index.tsx
> +          <img className="item-img" src={src} alt={alt} />
`alt`까지 !! 정말 꼼꼼하시네용 👍

2022-10-14 13:37 UTC, byhhh2 commented on src/pages/HomePage/index.tsx
> +        <TravelCard
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ `map`이 보고싶다 🥲

2022-10-17 06:57 UTC, DomMorello commented on src/component/TravelCard/index.tsx
> +            KRW {lowestPrice} <span aria-hidden>~</span>
aria-label 을 사용해야 할 것 같습니다! 모바일에서는 KRW 라고 직접 읽더라고요ㅠ

2022-10-17 06:58 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +  });
ㅋㅋㅋㅋㅋㅋㅋㅋ 신기하네요 :)

2022-10-17 06:59 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +    const listItem = scrollContainer.current.childNodes[0] as HTMLUListElement;
오 깔끔한 방법인 것 같습니다!

2022-10-17 06:59 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +    const containerStyle = getComputedStyle(scrollContainer.current);
지식을 공유하게 됐다니 정말 기쁘군요!

2022-10-17 07:00 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +      containerStyle.getPropertyValue("gap").substring(2, 0)
그런데 코드가 css 속성에 의존하고 있는 면이 한계점인것 같습니다ㅠ 만약에 flex 와 gap 을 사용하지 않고 다른 방식을 사용한다면 이 코드도 같이 보수가 돼야 하는 단점이 있습니다ㅠ

2022-10-17 07:01 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +      scrollContainer.current.scrollLeft >= (itemWidth + itemMargin) * 5;
아 저도 이 부분이 좀 그랬는데 그렇게 하는 방식도 좋을 것 같습니다!

2022-10-17 07:03 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +      scrollContainer.current.scrollLeft += itemWidth + itemMargin;
오 새로운 함수를 알게 됐습니다 감사합니다! ㅎㅎ

2022-10-17 07:03 UTC, DomMorello commented on src/component/TravelCard/index.tsx
> +          <img className="item-img" src={src} alt={alt} />
넵 접근성의 기본! ㅎㅎㅎ

2022-10-17 07:04 UTC, DomMorello commented on src/pages/HomePage/index.tsx
> +        <TravelCard
아무래도 하드코딩보다는 변화에 유연하게 dummy 데이터와 map을 활용하도록 수정하겠습니다 ㅎㅎ

2022-10-17 08:25 UTC, DomMorello commented
## 피드백 반영
> 무비~ 정성껏 피드백 작성해주셔서 감사합니다! 많은 것들을 배우고 부족한 부분을 인지했습니다!
최대한 반영해서 코드를 수정했는데 다시 한 번 확인해주시면 감사하겠습니다! 

### 더미데이터 생성
TravelCard 컴포넌트에 들어갈 더미데이터 생성으로 추후 변화에 유연하도록 코드를 개선했습니다! 

### KRW 접근성 개선
KRW 일부 디바이스에서 KRW 를 그대로 읽는 부분을 개선하기 위해 `aria-label`을 사용해서 개선했습니다.

### 다음 버튼 비활성화 로직 개선
하드 코딩으로 `* 5` 이었던 부분을 `scrollWidth` 와 `offsetWidth` 를 활용해서 계산식을 개선했습니다.

### type assertion 제거
childNodes 의 타입을 지정해줘서 type assertion 을 제거했습니다.

2022-10-17 09:38 UTC, byhhh2 approved these changes
확인했습니다 하디~~ 👍
수고하셨어용 😆

<img width="300" alt="" src="https://user-images.githubusercontent.com/52737532/196144399-4ecb3419-d58f-4394-ab29-ab8bd72a2d6e.png">

(계산 흔적 꿀잼이네요 ㅋㅋ😁)

2022-10-17 09:39 UTC, merged