[항공사 웹사이트의 컴포넌트 접근성 높이기 - 2단계] 코카콜라(강인태) 미션 제출합니다.
woowacourse/a11y-airline pull request #71
Opened 2022-10-12 12:13 UTC by intae92

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

[링크](https://intae92.github.io/a11y-airline/)

## ✅ 요구사항 목록

**1 Spin Button**

- [x] 최대 인원수는 3명까지만 가능하게 구현합니다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
성인 탑승자 한명 줄이기 버튼
성인 1 텍스트 숫자만 수정
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 2
성인 탑승자 한명 늘리기 버튼
성인 승객 추가 3
```

**2 Carousel**

- [x] 총 8개의 carousel 중 2개의 목록을 기본으로 보여준다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
1. 지금 떠나기 좋은 여행
2. 목록 8개 항목 포함 서울/인천 로스앤젤레스 일반석 왕복 1,481,800 대한민국 원 링크 목록 항목
3. 다음 버튼 (사용 중지)
4. 이전 버튼 (사용 중지)
```

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

키보드로 화면을 컨트롤 할 때, 신경써야 하는 부분이 많네요. 록바는 어느 부분에 좀 더 신경을 쓰고 개발을 하시나요?

2022-10-14 01:57 UTC, moonheekim0118 commented
- 슬래쉬 , 물결기호까지 읽어버려요!
- 모바일에서 버튼 UI의 위치가 깨져요!
- 모바일에서 다음버튼이 보이지 않아요 ㅠ _ ㅠ

2022-10-16 07:55 UTC, lokba requested changes
콜라 형님 반갑습니다. 
카카오가 끊긴 것처럼, 제 정신도 끊겨버려서 리뷰가 늦어졌네요.🙇‍♂️

우선 코드 잘봤습니다. 
시맨틱 태그를 적절하게 잘 활용하셔서, 스크린리더기가 자연스럽게 읽는 것을 확인했습니다. 
더미 데이터를 상세하게 설계하신 부분과 스타일링에도 디테일하게 신경쓰신 부분에서 꼼꼼함 배웠습니다. 


호프가 남긴 부분은 제외하고 코멘트 드렸습니다. 
코멘트 남겼으니 한번 확인해주세요😎 (이번 코멘트도 RCA룰을 적용해봤습니다.)

---
### RCA 룰
r:   반영해주실래요? (Request changes)
c:  의견을 듣고 싶어요. (Comment)
a:  답변을 굳이 안 달아도 됩니다~ 그냥 사소한 의견이에요. (Approve)

2022-10-16 07:55 UTC, lokba commented on public/index.html
> +    <title>미션2 Carousel: 지금 떠나기 좋은 여행</title>
a : 👍

2022-10-16 07:55 UTC, lokba commented on src/layout/CarouselPage.tsx
> +type TripListType = {
r : wow....정말 상세하게 데이터 설계하셨네요. 멋지십니다. 💯 `TripListType` 보다는 `TripType`이 맞을 것 같은데 어떻게 생각하시나요?

2022-10-16 07:55 UTC, lokba commented on src/layout/CarouselPage.tsx
> +  departureAirportNm: string;
c : Nm이 Num의 약자인 줄 알았는데, mock 데이터를 보니 Num이 아닌 것 같네요. Nm이 무슨 뜻인가요?

2022-10-16 07:55 UTC, lokba commented on src/layout/CarouselPage.tsx
> +                <li key={trip.id} css={styles.li}>
a : 저는 이런 디테일 너무 좋아요. trip 더미 데이터에 의도적으로 id를 넣어서 `index`가 아닌 `trip.id`를 사용하는거 신경쓴거 같아서 좋네요👍

2022-10-16 07:55 UTC, lokba commented on src/layout/CarouselPage.tsx
> +    setDisableLeftButton(true);
c : disableLeftButton의 초기값을 true로 세팅하는 거는 어떠신가요?

2022-10-16 07:55 UTC, lokba commented on src/layout/styles.ts
> +  margin-bottom: 16px;
c : 🧚
```suggestion
  margin: 0 0 16px;
```

2022-10-16 07:55 UTC, lokba commented on src/mocks/data.json
> +  "specialOfferList": [
a : 더미 데이터 구성하는데 오래 안걸리셨나요?😮

2022-10-17 13:57 UTC, merged