[항공사 웹사이트의 컴포넌트 접근성 높이기 - 2단계] 밧드(감우영) 미션 제출합니다.
woowacourse/a11y-airline pull request #89
Opened 2022-10-13 07:19 UTC by kamwoo

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

[링크]()

## ✅ 요구사항 목록

**2 Carousel**

- [x] 총 8개의 carousel 중 2개의 목록을 기본으로 보여준다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
1. 지금 떠나기 좋은 여행
2. 목록 8개 항목 포함 서울/인천 로스앤젤레스 일반석 왕복 1,481,800 대한민국 원 링크 목록 항목
3. 다음 버튼 (사용 중지)
4. 이전 버튼 (사용 중지)
```

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-10-14 02:09 UTC, DomMorello commented
안녕하십니까! 모바일 접근성 테스트 피드백 드리겠습니다!

- [ ] 첫 화면에서 모바일 뷰에 꽉 안 들어오고 넘치게 렌더돼서 다음 버튼은 아예 시각적으로 볼 수가 없습니다
- [ ] 서울/인천 을 따로 읽고 하이픈을 따로 읽고 두바이를 따로 읽는 부분이 어색합니다!
- [ ] KRW를 그대로 읽습니다. 그리고 캐러샐이미지 내부 텍스트들 전부에 링크 라고 읽는게 조금 헷갈릴수 있을것같습니다.
- [ ] 버튼에 포커스를 하면 '다음 목록 버튼 앤드 지금떠나기좋은여행 영영 앤드 주여(?)' 라고 읽는게 이상하네요ㅠ

2022-10-14 02:10 UTC, wonsss commented
## carousel 안의 이미지 영역에서 정보를 의미를 드러내서 알려주는지 체크합니다.

예) 금액 정보를 의미를 잘 드러내면서 알려주는지 체크합니다. (실제로는 1,157,500 대한민국원 으로 한국 금액임을 쉽게 알려줄 수 있습니다. - OS별 보이스오버에 따라 다를 수는 있음)

- 모바일에서는 띄어쓰기 단위로 다 끊어서 읽는 것 같아요.

## 캐로우셀의 다음 버튼을 이용해 마지막 이미지까지 이동하고 나면, 더이상 이동할 수 없다는 것을 알려줘야 합니다.

모바일에서는 읽어주진 않는 것 같아요

2022-10-14 04:21 UTC, al-bur requested changes
안녕하세요 밧드 앨버입니다!

2단계도 고생 많았어요
몇 개의 코멘트 남겼습니다 확인 부탁해요🎈🎈

2022-10-15 14:23 UTC, kamwoo commented on src/components/Card/index.tsx
> +    <a href='https://www.koreanair.com/kr/ko' className={S.layout} tabIndex={props.tabIndex}>
요구사항을 맞출려고 했습니다. 
![3ED6CBFE-6918-466A-A19D-F96916D651A4](https://user-images.githubusercontent.com/61308364/195991469-d17f2dce-60e9-4160-8c2d-4b119f0c54d6.png)

처음 탭으로 이동했을 때, 첫번째 아이템을 포커스하고 바로 버튼을 포커스하는게 사용성에 좋겠다고 생각했어요.
만약에 아이템을 모두 지나고 나서 버튼을 포커스하면 무슨 소용이 있겠나 싶었습니다.
그래서 아이템 포커스 후에 바로 버튼을 포커스하도록 tabIndex를 사용했어요

2022-10-15 14:29 UTC, kamwoo commented on src/components/Carousel/index.tsx
> +            <li key={info.id} role='listitem' tabIndex={-1}>
처음에 ul과 li를 태그를 사용하지 않고 구현해서 `role="list"`와 `role="listitem"`을 사용해서 목록이라는 것을 알려줬습니다.
태그만으로도 잘알려주네요 👍

2022-10-15 14:31 UTC, kamwoo commented on src/components/Carousel/Carousel.module.css
> +  clip: rect(0, 0, 0, 0);
보이지 않도록 style할 때 사용했었는데, 이게 왜 여기있지..? 
안써서 지웠습니다.

2022-10-15 14:33 UTC, kamwoo commented on src/pages/CarouselPage/index.tsx
> +        <h1 id='TRIP_HD'>지금 떠나기 좋은 여행</h1>
특별한 이유는 없습니다. 가이드를 보면서 생각했던게 단지 aria-label을 위해서 붙여준 id라서 이렇게 구분해주지 않나 생각합니다. 흠..

2022-10-15 14:38 UTC, al-bur commented on src/components/Carousel/index.tsx
> +            <li key={info.id} role='listitem' tabIndex={-1}>
li 태그에는 이미 role=listitem가 암시적으로 설정되지 않나요?!?!

![image](https://user-images.githubusercontent.com/64825713/195992260-c5650340-425c-488f-9fc8-2caf7a773ab2.png)

2022-10-15 14:38 UTC, kamwoo commented on src/components/Carousel/index.tsx
> +        tabIndex={0}>
위 코멘트에 같이 적었어요!

2022-10-15 14:44 UTC, kamwoo commented on src/components/Card/Card.module.css
> +.layout:link {
방문하지 않은 링크 선택자인데, 구현하는 과정에서 사용했다가 안지웠네요. 👍

2022-10-15 14:54 UTC, kamwoo commented on index.d.ts
> +declare module '*.module.css';
typescript가 css 파일을 module로 인식하지 못해서 추가해줬습니다.

2022-10-15 15:47 UTC, kamwoo commented on src/components/Carousel/index.tsx
> +      carouselRef.current.scrollBy({ left: 256, behavior: 'smooth' });
cardItem들을 ref를 통해서 연결시켜서 left position의 차이만큼 이동시키는 방식으로 수정했습니다!

2022-10-17 10:19 UTC, kamwoo commented on src/components/Carousel/index.tsx
> +            <li key={info.id} role='listitem' tabIndex={-1}>
넵 그래서 "태그만으로도 잘알려준다고" 했습니다!

2022-10-18 00:58 UTC, al-bur commented on src/components/Carousel/Carousel.module.css
> +  clip: rect(0, 0, 0, 0);
좋습니다!

2022-10-18 01:18 UTC, al-bur approved these changes
밧드 2단계 고생하셨습니다~

2022-10-18 01:18 UTC, merged