[항공사 웹사이트의 컴포넌트 접근성 높이기 - 2단계] 시지프(김의진) 미션 제출합니다.
woowacourse/a11y-airline pull request #90
Opened 2022-10-13 07:42 UTC by euijinkk

## 🔥 결과

직접 구현한 페이지를 작동시켜볼 수 있도록 접근 가능한 페이지 링크를 공유해주세요.

[링크](https://euijinkk.github.io/a11y-airline/)

## ✅ 요구사항 목록

**2 Carousel**

- [x] 총 8개의 carousel 중 2개의 목록을 기본으로 보여준다.
- [x] 실제 스크린 리더는 아래와 같이 읽을 수 있어야 합니다. 단, 스크린 리더기 마다 읽는 방법이 다를 수 있으니 참고만 해주세요. 중요한건 스크린 리더기를 활용하여 동작을 할 수 있어야 합니다.
- [x] 리팩터링 과정에서 불필요하거나 웹 표준에 어긋나는 마크업은 없는지 확인합니다.

```
1. 지금 떠나기 좋은 여행
2. 목록 8개 항목 포함 서울/인천 로스앤젤레스 일반석 왕복 1,481,800 대한민국 원 링크 목록 항목
3. 다음 버튼 (사용 중지)
4. 이전 버튼 (사용 중지)
```

## 🧐 공유

- 리액트에서 변수를 받아와서 글자를 보여줄때, 잘못하면 voiceover가 끊어서 읽게 되더라구요. 템플릿 리터럴로 잘 묶어줘야, 끊어읽지 않고 한번에 잘 읽어주네요! [참고링크](https://github.com/woowacourse/a11y-airline/commit/7c35e31dde9f8478b95e19c24f5122e9a3180ca6)
- alt를 비워주는게 오히려 좋은 선택일 수 있다는 것을 꺠달았습니다. alt를 읽어주는게 무의미한 경우가 있더라구요!
- carousel을 직접 width 계산해서 하려고 하니까 하드코딩이 많아지고 힘들더라구요 ㅠㅠ. 그리고 button이 클릭되는 상황과, tab으로 움직이는 상황이 구분되어버려서, tab으로 했을 때에는(+ 모바일에서 드래그하며 읽을때에) Next, Prev버튼을 Disabled 시켜주지 못 하고 있어요. 빅터는 어떻게 button이 클릭되는 상황과 tab를 누르는 상황을 커버하셨는지 궁금합니다.

2022-10-14 01:56 UTC, moonheekim0118 commented
- 슬래쉬 , 물결기호까지 읽어버려요!
- 모바일에서 버튼 UI의 위치가 깨져요!
- 모바일에서 다음버튼이 보이지 않아요 ㅠ _ ㅠ

2022-10-14 02:23 UTC, intae92 commented
1. 슬래시 읽음
2. 탭으로 이동시 왼쪽 버튼 비활성화 되어 있음

화이팅

2022-10-15 10:41 UTC, woose28 requested changes
시지프 안녕하세요~ 2단계 리뷰로 다시 만나게 됐네요!

먼저 공유 부분에 남겨주신 질문에 대한 답변입니다.

> carousel을 직접 width 계산해서 하려고 하니까 하드코딩이 많아지고 힘들더라구요 ㅠㅠ. 그리고 button이 클릭되는 상황과, tab으로 움직이는 상황이 구분되어버려서, tab으로 했을 때에는(+ 모바일에서 드래그하며 읽을때에) Next, Prev버튼을 Disabled 시켜주지 못 하고 있어요. 빅터는 어떻게 button이 클릭되는 상황과 tab를 누르는 상황을 커버하셨는지 궁금합니다.

맞아요 해당 부분을 처리하기 까다로워서 저도 애를 먹었습니다..!
우선 저는 scroll 이벤트와  활용해서 처리했습니다!  tab을 해서 다음 요소로 포커스가 넘어가는 경우에 scroll 이벤트가 발생하는 걸 확인했습니다. 따라서 scroll 이벤트 핸들러 내부에서 현재 scroll의 위치가 끝에 있다면 Next 버튼을 disabled 하는 로직을 구현했습니다! 반대로 scroll 위치가 처음 시작 위치라면 Prev 버튼을 disabled 하고요!

❗️ 현재 제출해 주신 코드에서도 테스트를 해보았는데요. StyledTravelList 스타일드 컴포넌트에 onScroll 이벤트를 등록하니 호출이 안되더라고요..! 대신 StyledWrapper 컴포넌트(overflow-x: scroll 스타일을 적용한 컴포넌트)에 onScorll 이벤트가 호출되는 것을 확인했습니다!  결론은 `overflow-x: scroll`로 스크롤을 허용한 컴포넌트에서 onScorll 이벤트가 호출되는 거 같아요! 해당 방법을 도입하신다면 참고하면 좋을 거 같아요~

접근성 관련해서 피드백은 다음과 같습니다.
1. 목록의 처음 위치에서 이전 스크린리더로 버튼을 누르면 비활성화됨을 알려주지만 이유를 알려주지 않습니다.
2. 캐로셀로 이미지 끝까지 확인한 후 이전 버튼을 이용해서 캐로셀 맨 앞으로 이동할 수 없습니다. 목록에 끝에 도착해도 이전 버튼이 여전히 비활성화돼 있어요..!

이 외에도 코드 단에서 피드백을 남겼으니 확인 부탁드립니다~!

2022-10-15 10:41 UTC, woose28 commented on src/Carousel.tsx
> +  overflow-x: scroll;
시지프도 x축에 대해서 스크롤을 허용해주셨네요! 저 또한 사용성을 위해 스크롤을 허용해주었습니다!
다만 기본적으로 스크롤이 멈추는 위치에 대한 제약사항이 없어서 스크롤이 애매하게 요소의 중간 위치에 멈추는 경우가 발생하게 됩니다!
위와 같은 현상은 카로셀 UI에 어울리지 않다는 생각이 들어요!

따라서 저는 스크롤의 위치가 각 카로셀 내부 각 요소의 시작 점에 멈출 수 있도록 제한을 두었습니다! 이를 위해 아래의 CSS 속성을 이용했습니다.

- [scroll-snap-type](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type): 스크롤이 멈추는 위치를 강제하는 방법에 대한 style 속성입니다.
- [scroll-snap-align](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-align): scroll-snap-type이 적용된 요소의 자식 요소에 지정하는 스타일입니다. 해당 스타일이 적용된 요소를 기준으로 어느 위치에 스크롤을 멈추게하는 지에 관한 style 속성입니다

카로셀 동작에 관한 제 개인적인 견해 포함된 부분이고, 정보 공유 차원에서 말씀드리는 것이니 해당 속성을 꼭 반영하실 필요는 없습니다!

2022-10-18 08:08 UTC, euijinkk commented on src/Carousel.tsx
> +                <img src={imageUrl} alt='' width={250} height={320.36} />
오오.. 그렇네요.. 수정했습니다!

[feat: img를 a 태그 안으로 넣기](https://github.com/woowacourse/a11y-airline/pull/90/commits/239baee2c254cc37c34beab2e78d430a86d1bf61)

2022-10-18 08:12 UTC, euijinkk commented on src/Carousel.tsx
> +    };
넹.. 사실 반응형을 고려하려고 넣은 부분이었는데, 
반응형 부분을 차마 마무리하질 못했습니다..!

2022-10-18 08:16 UTC, euijinkk commented on src/Carousel.tsx
> +  overflow-x: scroll;
와 미쳐따!! 완전 유용할거같아요. 프로젝트에 한번 적용해봐야겠다는 생각이 들었습니다!

근데 저 overflow scroll 속성은... 실험 한다고 실수로 넣은 것이라.. 하하 원래 hidden으로 되돌려놓겠습니다!

2022-10-18 08:58 UTC, euijinkk commented
scrollTo 메서드를 사용해본 적이 없어, 하드코딩 했었네요! 
그러다보니, scrollEvent가 아니라 translate 를 제어했구요.
그러다보니, scroll 로 인한 이벤트와, translate 이벤트가 나누어져서 tab과 버튼 클릭이 구분되어 버렸군요.

근본적으로 scroll 이벤트로 제어했구요, scrollTo 메서드와 onScroll 이벤트를 활용했습니다.
그 과정에서 디바운스를 걸어보았어요!

좋은 피드백 감사합니다!
수정사항 반영했습니다.

2022-10-18 09:15 UTC, merged